### ISSUE TITLE
Commit 71075161f39eecfa56ac440da09c3a3a33cb69bb appears to break --extra-cflags option

### ISSUE THREAD

**Issue by fred-anderson** [rhash/RHash#100]
I pass --extra-cflags=-fPIC to the configure script when building because I include rhash in a .so later. The latest commit causes the configure script to error off with the message:

./configure: 223: ./configure: -fPIC: not found

The previous commit works as expected.

**Comment by rhash** [comment]
Fixed by cc97c9bc7dbc81bcfd87f34e5886f63ba2ae71e7

**Comment by rhash** [comment]
Fix included in v1.3.9.
