### ISSUE TITLE
rhash: error while loading shared libraries: librhash.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Rebolon** [rhash/RHash#101]
On a Centos 7
i tried to install rhash (i've already installed on 2 others servers this year).

 * clone the project
 * ./configure --sysconfdir=/etc --exec-prefix=/usr --enable-lib-static
 * make install install-lib-so-link install-lib-shared

But when i do rhash, i get `rhash: error while loading shared libraries: librhash.so.0: cannot open shared object file: No such file or directory`

I also tried to do `make install-headers` but it said that no rules exists for target install-headers

Thanks for help

**Comment by rhash** [comment]
Try to fix it by running `ldconfig` as root,
also verify that the library is properly installed: `ls -l /usr/lib/librhash.so.0`.

The command to install headers is now `make install-lib-headers`.

**Comment by LukeLIN-web** [comment]
I am running cmake in conda, may you know how to invoke it from conda env?
