### ISSUE TITLE
fatal error: incompatible librhash version

### ISSUE THREAD

**Issue by z3r0byt3s** [rhash/RHash#105]
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

/usr/local/bin/rhash
fatal error: incompatible librhash version

```

**Comment by rhash** [comment]
This is expected behavior in your case.

**Comment by z3r0byt3s** [comment]
?? so what to do

**Comment by rhash** [comment]
Link rhash with a compatible librhash version (v1.3.8 - v1.3.9). To see which librhash is currently loaded run 'ldd /usr/local/bin/rhash'.

Possible ways to fix are:
* install a deb package with the latest librhash, e.g. the package from the Debian Unstable
* compile with librhash statically (./configure --enable-static)
* set rpath to the directory with correct shared library
* install rhash and librhash into /usr/ (./configure --prefix=/usr)

**Comment by z3r0byt3s** [comment]
./configure --enable-static

helped thx so much !!!
