### ISSUE TITLE
GitHub-generated tarballs may get re-created and invalidate the signature

### ISSUE THREAD

**Issue by mbakke** [rhash/RHash#108]
Hello,

Thank you for providing cryptographic signatures of the RHash source code!  Unfortunately the GitHub "archive" downloads are prone to getting re-created, with different time stamps.

Please consider uploading "releases" instead, even if they are identical to the currently generated archives.  That way the URL (and cryptographic signature) will stay valid 'forever'.

**Comment by rhash** [comment]
For now all tarballs remain unchanged and all signatures are valid.
Could you provide a link proving that GitHub sometimes recreates tarballs?

BTW, signed tarballs are mirrored at:
1. https://sourceforge.net/projects/rhash/files/rhash/
2. https://snapshot.debian.org/package/rhash/

**Comment by danfe** [comment]
That's why I always prefer SF downloads over GitHub's. :-)  Please keep uploading new release versions there, despite that development happens here.

**Comment by mbakke** [comment]
I have tried contacting GitHub about it, but they are not responding.  We've seen it happen repeatedly in a downstream distribution for less-popular repositories.

Closing since the tarballs are mirrored at SourceForge.
