### ISSUE TITLE
hashing STDIN and separation

### ISSUE THREAD

**Issue by TheRinger** [rhash/RHash#109]
Is it currently possible to hash stdin that is separated by a default like newline - '\n' or ; I would like to cat $FILE|rhash --sha256 - and get a unique hash per line but as of now I've only found that It will hash the full stdin as one hash. there are slow bash work arounds like for line in $(cat $FILE);do echo $line|rhash --sha256 -;done but that is so slow it takes away from the power or rhash. Is this something that already exists that perhaps isn't explained well? Atm I'm using hashrat for this process as it has a -rawlines or -lines arg allowing you to strip the whitespace or leave it.
If I'm in wrong place for feature requests, I apologize. Thanks for your patience

**Comment by rhash** [comment]
You should write scripts for such tasks:

~~~py
#!/usr/bin/python3
# Usage: sha256-lines.py FILE...
import rhash
import sys

def print_sha256(msg):
  print(rhash.hash_for_msg(msg, rhash.SHA256))

if __name__ == '__main__':
  for path in sys.argv[1:]:
    with open(path) as f:
      for line in f:
        print_sha256(line.rstrip('\n'))
~~~

The script requires [rhash.py](https://github.com/rhash/RHash/blob/master/bindings/python/rhash.py) python module and librhash.so/librhash.dll library.

How to use it:
~~~sh
$ printf "\na" > file.txt
$ ./sha256-lines.py file.txt
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb
~~~

**Comment by TheRinger** [comment]
Thanks I do use something similar, I am somewhat fluent in python but not C
, I thought it would be a useful feature but perhaps there is a reason why
the 3 lines of code were never implemented
