### ISSUE TITLE
[RESEARCH] GOST R 34.11-2012 aka Streebog?

### ISSUE THREAD

**Issue by sergeevabc** [rhash/RHash#11]
Сегодня RHash поддерживает выходящий из употребления отечественный хэш GOST R 34.11-94, который сменяется «[Стрибогом](https://tc26.ru/research/polozhenie/GOST_R_34_11-2012_eng.pdf)», Известно несколько наших реализаций (Казимирова, Лебедева, Дягтерёва, авторского коллектива — см. [сравнение производительности](http://www.ruscrypto.ru/resource/summary/rc2014/03_borodin_rybkin.pdf) за 2014 год), есть и [зарубежные](http://www.stribob.com/stricat/).

Когда ожидать в RHash? Так сказать, на волне импортозамещения.

**Comment by sergeevabc** [comment]
А с другой стороны, Стрибог для файлого хэширования уж очень медленный.

**Comment by rhash** [comment]
Это русский стандарт, который нужен многим, надо поддерживать в любом случае.

**Comment by sergeevabc** [comment]
Вы видели массовое применение Стрибога вне госучреждений РФ, где это часть электронных подписей? Вот добавили его в Veracrypt (август 2016), но многие пользуются для хэширования файлов — вопрос.

![](https://vgy.me/1qG2fK.png)

**Comment by sergeevabc** [comment]
Вопрос ждал решения 3 года. Видимо, это не актуально. Закрываю.

**Comment by rhash** [comment]
GOST R 34.11-2012 is implemented in the RHash v1.3.8.

**Comment by sergeevabc** [comment]
Работает, спасибо.
