### ISSUE TITLE
Visual C++ Builds slower than those available at SourceForge

### ISSUE THREAD

**Issue by DvdKhl** [rhash/RHash#115]
I've cloned the repo (Tag 1.3.9) and build (x64 Release) it with Visual Studio 2019 (I had to upgrade to Toolset v142).
And then compared the SHA3 hash speeds with https://sourceforge.net/projects/rhash/files/rhash/1.3.9/ :

PS D:\Downloads\RHash-1.3.9\build\vc-2010\Release-x64> .\rhash.exe --speed --sha3-256 "F:\A.mkv"
8854e2c29a98c1b2558ae79b0041684cadebd9cb4b850434d66d19832969fa5a  F:\A.mkv
Calculated in 4.501 sec, 155.10 MBps

PS D:\Downloads\rhash-1.3.9-english-win64-2\RHash-1.3.9-english-win64> .\rhash.exe --speed --sha3-256 "F:\A.mkv"
8854e2c29a98c1b2558ae79b0041684cadebd9cb4b850434d66d19832969fa5a  F:\A.mkv
Calculated in 2.675 sec, 260.96 MBps

Is there something I need to change first or is there some issue with the v142 toolset and RHash?

**Comment by rhash** [comment]
Binaries at SourceForge are built using [Mingw-w64](http://mingw-w64.org/). 

Currently RHash is not benchmarked/optimized for VC++, due to my lack of time.
