### ISSUE TITLE
No header files installed on `make install`

### ISSUE THREAD

**Issue by dilyanpalauzov** [rhash/RHash#116]
Calling `make install` in RHash-1.3.9 installs `librhash.so.0` but no rhash.h. So cmake cannot find the systems’s librhash, see https://gitlab.kitware.com/cmake/cmake/-/issues/20728#note_762319 .

**Comment by danfe** [comment]
There is no bug in RHash here.  Header files are installed together with static archives via `install-lib-static` target.  If you want it to be invoked automatically, run the `configure` script with the `--enable-lib-static` switch.  Notice that it is passed in the provided `rhash.spec.in` file.  If your OS/distribution does not do that, you might want to report a bug against them instead.

**Comment by dilyanpalauzov** [comment]
There is no point to install header files only with static build, as the header files are equally.needed with dynamic libraries.

I use Linux From Scratch and rhash.spec.in virtually does not exist there.

**Comment by danfe** [comment]
> There is no point to install header files only with static build, as the header files are equally needed with dynamic libraries.

No.  Header files are needed for _building_ consumers of a library (that's why they go with what some distributions call `-dev` or `-devel` packages).  During run-time linking, only shared libraries are needed, not headers.

> I use Linux From Scratch and `rhash.spec.in` virtually does not exist there.

It's part of the RHash source code, the template for RPM `.spec` file.  I don't know how packages are managed in LFS, I've only suggested it as a reference.

**Comment by dilyanpalauzov** [comment]
In LFS there are no packages.  Only .tar.gz.

**Comment by dilyanpalauzov** [comment]
There is no differences between linking for consumers of the library and run-time linking.  When compiling software depending on librhash, one has to decide whether librhash will be linked statically or dynamically.  In both cases the header files are needed.  This is how all software distributed in source form (and especially libraries) work.

Can you provide an example of another library distributed in source code, that on `make install` does not install the headers ? (except nss, nspr, and llhttp)

**Comment by danfe** [comment]
> There is no differences between linking for consumers of the library and run-time linking.

Of course there is (you've missed the _building_ part).

> This is how all software distributed in source form (and especially libraries) work.

Thank you for educating us on that. :-)  Now, if you want static libraries (object archives) and header files to be installed automatically, simply `./configure` RHash with `--enable-lib-static` switch as suggested earlier.

**Comment by cztk** [comment]
omg just wow, I'd like to give it a thumbs down.
If I develop software in something else than a dumb editor and documentation alone there is a need for simple h files in every IDE. At the same time I do not want to have static libs.
Or do I miss something here? Would young pups be hurt to install the headers along the shared lib aswell?

**Comment by rhash** [comment]
RHash project itself is not a library project, so `make install` installs by default only rhash binary with its dependencies, but without (unnecessary for running) development headers, static library or the _librhash.so_ symlink.
