### ISSUE TITLE
Install librhash.so on `make install`

### ISSUE THREAD

**Issue by dilyanpalauzov** [rhash/RHash#117]
On `make install` Rhash 1.3.9 installs `/usr/local/lib/librhash.so.0`, but does not install `/usr/local/lib/librhash.so`.  

Then cmake cannot find librhash.so on the system, see https://gitlab.kitware.com/cmake/cmake/-/issues/20728#note_762345 and the comments that follow.

In particular, there are some rules followed by `ldconfig`, which I do not remember exactly, how to generate the symlinks, based on SONAME and such things.  Creating manually the link `librhash.so → librhash.so` does not help cmake to find librhash.  Also, after the symlink is created manually and `ldconfig` is run, `ldconfig -p |grep rhash` prints only the the file with `.so.0` at the end.

**Comment by danfe** [comment]
This is not a bug in RHash.  The `librhash.so` symlink is installed by the `install-lib-so-link` target.  Typically, correct (complete) installation targets are `install install-lib-so-link install-pkg-config` trinity.

**Comment by dilyanpalauzov** [comment]
Please include the install-lib-so-target in the install target.

Software has to agree on common build process.  All other sofrware installs on 'make install' symlinks.  With its distinct approach librhash just makes the lives of its users more complicated and this complication does not provide any advantages.

**Comment by rhash** [comment]
RHash project itself is not a library project, so `make install` installs only rhash binary with its dependencies, but without (unnecessary for running) development headers, static library or the _librhash.so_ symlink.
