### ISSUE TITLE
README: no such thing as a 'hash sum' exists

### ISSUE THREAD

**Issue by requiredregistration** [rhash/RHash#118]
https://github.com/BLAKE3-team/BLAKE3

-

in the README you call all the outputs 'hash sums'. no such thing as a 'hash sum' exists. that needs to be corrected.

checksum algos: checksums
cryptographic hash function algos: message digests

checksums:
CRC32
CRC32C

message digests:
the rest

**Comment by rhash** [comment]
Fixed by 63b4c376aa326b6a19dfeb19342e8c54d022c2fb, eea184365ddac1d7511ccd43fa620f04b63d7515 and e2cc2b9a151cc053588914a8edb69aa943798ed2.

@requiredregistration, please check if docs are correct now.

**Comment by rhash** [comment]
Included into release **v1.4.0**.
