### ISSUE TITLE
Blake2

### ISSUE THREAD

**Issue by sergeevabc** [rhash/RHash#12]
Алексей, присмотритесь к [Blake2][1], пожалуйста.
Сравнивал рядом `rhash --md5` и `b2sum` ([скачать][2]), скорость одна.
Собираетесь ли поддерживать его?

[1]: https://blake2.net/
[2]: https://blake2.net/b2sum-bin_20130305.zip

**Comment by sergeevabc** [comment]
Алексей, мяу?

**Comment by rhash** [comment]
к сожалению не собираюсь. Полгода как нет возможности поработать над проектом, но если появится, то есть срочнее задачи)

**Comment by sergeevabc** [comment]
Из хэш-функций последнего времени, кажется, лишь Blake2b пробил себе дорогу, а его нет.

**Comment by z0hm** [comment]
**Алексей**, на **Blake2** попрежнему времени нет?

**Comment by sergeevabc** [comment]
Гм, а зачем завели новую тему (#52), если есть эта?
