### ISSUE TITLE
Print line_num before return when processing a binary string in check_hash_file

### ISSUE THREAD

**Issue by Comaxim** [rhash/RHash#120]
Help find binary lines when checking.
https://github.com/rhash/RHash/blob/d6f5777e8a3eae69f3985958bf82cb958064bad4/calc_sums.c#L534-L540

**Comment by rhash** [comment]
Good idea :)

**Comment by Comaxim** [comment]
Thanks!

**Comment by rhash** [comment]
Implemented by commit 296e73828dba239e28b18a3a1b2fa7e4bbf81f7b.

**Comment by rhash** [comment]
The change is included into **RHash v1.4.0**.
