### ISSUE TITLE
Base-32 encoding length problem

### ISSUE THREAD

**Issue by carlos-ls** [rhash/RHash#126]
As every 5 bytes encode as 8 bytes, isn't Base-32 encoded string expected length a multiple of 8? This code in librhash/hex.h

`#define BASE32_LENGTH(bytes) (((bytes) * 8 + 4) / 5)`

should probably be instead

`#define BASE32_LENGTH(bytes) ((((bytes) + 4) / 5) * 8)`

**Comment by rhash** [comment]
Indeed, any 5 bytes are encoded as 8 symbols from the base32 alphabet, for example `BASE32(0x AA BB CC DD EE) = 'VK54ZXPO'`.

The macro `BASE32_LENGTH(bytes)` returns the length of the base32-string for a given number of 8-bit bytes.

Let's check the formula for 5 bytes: `BASE32_LENGTH(5) = (((5) * 8 + 4) / 5) = (40 + 4)/5 = (int)(44/5) = 8`.
