### ISSUE TITLE
[Suggestion] Add xxHash support.

### ISSUE THREAD

**Issue by frenchiveruti** [rhash/RHash#134]
Hello I saw [only one issue related](https://github.com/rhash/RHash/issues/26) but it's in russian, is xxHash support planned? 
if not, what's the alternative?
 Thanks

**Comment by rhash** [comment]
Hello, xxHash support is not planned, mainly due to my time shortage.
Also, the number of supported hash functions is currently limited by 32, and addition of new algorithms requires serious core rewrite.
