### ISSUE TITLE
%{mtime} output format option returns incorrect date when used with the --file-list option

### ISSUE THREAD

**Issue by gonogo** [rhash/RHash#136]
I'm generating hashes of files by using the _--file-list_ option to feed rhash with a list of files I've generated previously using _'find'_.

`rhash --md5 -p '%h,:%p:,%s,%{mtime}\n' --file-list paths.txt`

The output from this operation will consistently return the date 1970-01-01 01:00:00 for each file in _paths.txt_. (In case you're wondering, I'm using the colons as a safe quote character to use for when I later import into a database, it's the only character you can be sure you won't find in a filename on a Mac)

If I run rhash without the _--file-list_ option and only specify a single file, the modified date of the file is output correctly using the same command shown above.

I'm running MacOS Mojave 10.14.6 with rhash v1.4.0 installed using Homebrew.

Is this a bug or am I using this option incorrectly? Thanks!

**Comment by rhash** [comment]
Thank you for reporting this bug!

It is fixed by commit 0eba12257e417c321ef50b48f2ce7081fdd278e3.
