### ISSUE TITLE
Two separate results of hash 

### ISSUE THREAD

**Issue by ihsanhaikalz** [rhash/RHash#14]
I have tried to get hash result using several hash algorithms using your program but I get two separate messages as follow:
./rhash -H --md5 trukrip 
trukrip  a5516e26c5c8f4c7248b94eddae57f57  f890d4a6533c995107bacd97f71f894131f45569

Could you tell me which one is the hash results? And what does the another message mean?

Thanks

**Comment by rhash** [comment]
You should specify one option instead of two, or choose another format like
--bsd or --printf=PRINTF_FORMAT. Consult the manual ;)

**Comment by rhash** [comment]
Hello,
run ./rhash --bsd -H --md5 trukrip
than you see hash names.

  Regards,
  Aleksey
