### ISSUE TITLE
Static build fail

### ISSUE THREAD

**Issue by pedroalbanese** [rhash/RHash#142]
Greetings,

Why can't I compile statically version 1.38 and later?  Cannot static link librhash.so.0

Thanks in advance.

**Comment by cztk** [comment]
more output would be nice, compile log? do you try --with-openssl but do not have static openssl lib?
I just built a satic lib with 1.4.1 no problems

**Comment by rhash** [comment]
@pedroalbanese The name _librhash.so.0_ contains suffix .so, meaning it's a _shared_ library. So you are somehow trying to statically link with a shared library.

* To compile RHash statically linked, run `./configure --enable-static && make clean all`.
* To compile and install _static_ LibRHash library run `./configure --enable-lib-static && make clean all install-lib-static`.

BTW, the RHash project itself is not a library project, so `make install` installs only rhash binary with its dependencies, but without (unnecessary for running) development headers, static library or the _librhash.so_ symlink.

**Comment by pedroalbanese** [comment]
Hi Aleksey, it is a great honor to chat with you. My case is a little delicate because I was trying to cross-compile from an amd64 to an Android armel.

I managed to compile version 1.2.10 with the command "make CC=arm-linux-gnueabi-gcc" but I can't do the same with later versions. I tried to follow the steps described but when I try to compile I get the following error message:

´root@cce:~/Área de trabalho/RHash-1.4.1# make CC=arm-linux-gnueabi-gcc
arm-linux-gnueabi-gcc calc_sums.o hash_print.o common_func.o hash_update.o file.o file_mask.o file_set.o find_file.o hash_check.o output.o parse_cmdline.o rhash_main.o win_utils.o librhash/librhash.a    -static -lcrypto -o rhash
/usr/lib/gcc-cross/arm-linux-gnueabi/10/../../../../arm-linux-gnueabi/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
make: *** [Makefile:158: rhash] Error 1´

But I have no idea how to solve it. I had the same problem when trying to compile statically OpenSSL and GOST Engine together (I don't know how to run non-static binaries on Android). I had a lot of difficulty and I couldn't do it hehe. I'm not actually a Linux user, so that was pretty predictable.

I ended up having to write an alternative (much more modest) in golang that I called GOSTTk (https://github.com/pedroalbanese/gosttk), to have support for Kuznechik and Streebog on Android. I was inspired by RHash and GOST Engine and I admire your work a lot.

**Comment by rhash** [comment]
For cross-compilation you should use the following commands:
~~~sh
./configure --cc=arm-linux-gnueabi-gcc --target=arm-linux-gnueabi --enable-static --disable-openssl --disable-gettext
make clean all
~~~

* The `--disable-openssl` option can be replaced by `--enable-openssl=runtime` or `--enable-openssl` by you will need to install dynamic libraries required by the build process.
* As I mentioned before, the `--enable-lib-static` option can be added to install static LibRHash library.
