### ISSUE TITLE
EDON-R/384 Result Size Error

### ISSUE THREAD

**Issue by andreas-kupries** [rhash/RHash#144]
The function `rhash_edonr384_init()` sets the result size to `224` (i.e. 160 bits less than it should be, I believe).
See https://github.com/rhash/RHash/blob/314423fb7a0e0a6bd49c5ac2050f537f72861eeb/librhash/edonr.c#L102
for the offending line.

**Comment by rhash** [comment]
Thanks for reporting this issue! It's fixed by d59ffdf1afacd7cd4cc7f57cb42d8ac6ece285af.

**Comment by andreas-kupries** [comment]
You are welcome. (Do I (have to) close the ticket now ? What with the `done` label and still open).

FYI, the issue was originally found when testing https://github.com/andreas-kupries/ankh and the hash results were unstable in the lower bytes (i.e. random memory data).
