### ISSUE TITLE
Allow to run 'check' and detect new files created (with 'recursive' option)

### ISSUE THREAD

**Issue by j1warren** [rhash/RHash#145]
Just a thought to consider.

When I run `rhash -r dir -o output.file` and later check it `rhash -c output.file`, it won't detect new files created in this directory.
Would be nice if one could combine  `-c` option with `-r` like `rhash -r dir -c output.file`, so it would check hashes from output.file and also detect if new files were created in that directory.

**Comment by rhash** [comment]
As a workaround you should run the following commands:
~~~sh
rhash -u output.file
rhash -c output.file
~~~

It probably would be useful to allow combining of `-u` and `-c` options to avoid re-checking of newly added files.

**Comment by rhash** [comment]
FR is implemented by commit

> 60528db61a0201a99f99e122f3bae36dbf550388 Allow simultaneous usage of --update and --check options.


It got included into the [RHash v1.4.3](https://github.com/rhash/RHash/releases/tag/v1.4.3) release.
