### ISSUE TITLE
rhash -c doesn't seem to parse a filename from the check file

### ISSUE THREAD

**Issue by chexum** [rhash/RHash#146]
I'm using rhash as a universal replacement for sha1sum -c/md5sum -c/sha256sum -c, but it seems to trip on a few types of lines.

Somehow it seems to interpret the hash part of the line as the filename.

Part of this seem to be that the '*' binary marker is missing, but that's how the file was generated, and otherwise sha1sum is happy with it.

```
# echo '1111111111111111111111111111111111111111  ROOT/usr/lib/tt2/templates/ps/mm'|rhash -c - 

--( Verifying (stdin) )---------------------------------------------------------
 1111111111111111111111111111111111111111            No such file or directory
--------------------------------------------------------------------------------
Errors Occurred: Errors:0   Miss:1   Success:0   Total:1  

```
Another way to repro (on Void, no options are enabled in /etc/rhashrc)
```
# rhash -V                   
RHash v1.4.0
# egrep '^[a-z]' /etc/rhashrc 
# mkdir -p ROOT/usr/lib/tt2/templates/ps
# touch ROOT/usr/lib/tt2/templates/ps/mm
# find ROOT -type f|xargs sha1sum|rhash -c -
```
(similar output as above)

**Comment by rhash** [comment]
Thank you for the bug report. The bug is fixed by 9105d546ea636b994337b71c976e1606306b1989.
