### ISSUE TITLE
RHash under TrustInSoft CI

### ISSUE THREAD

**Issue by jakub-zwolakowski** [rhash/RHash#147]
Hi,

I initiated the configuration of RHash on the new tool TrustInSoft CI. It's a source code analyzer, which analyzes execution paths (usually unit tests in your repo) to detect Undefined Behaviors along the way. Coverage includes all the defects that sanitizers ASAN, UBSan and MSan find, plus a large number of other (usually subtle) defects.

So I've [set up TrustInSoft CI](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/2) on most test cases from `librhash/test_hashes.c` and also some tests cases extracted by hand from `tests/test_rhash.sh`. It has found several Undefined Behaviors on the tested execution paths. For each test, TrustInSoft CI stops the analysis on the first UB, so I went step-by-step: provided a fix for the first UB, reviewed the updated analysis results, provided a fix for the next UB, etc. This is the typical workflow, usually we iterate like this until all tests are green.

You can see all the steps here: <https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash>

Below is a summary of suggested fixes (or workarounds, when I was not sure how to fix the UB properly) for the UBs that I've found. And some explanation.

Can you let me know if you find those results interesting?

### UBs and fix / workaround

| UB  | Message  | Problem  | Fix |
|:--- |:--- |:--- |:--- |
| [UB#1](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/2?page=1&test=1) | **Subtractions between pointers that may not point to the same allocated block** in function 'rhash_init_multi' in file 'librhash/rhash.c' line 130. | `(char*)(ptr) - (char*)0` | [FIXED](https://github.com/jakub-zwolakowski/RHash/commit/f56d74017a162ccbd796b97b8ae514330aa42c86) |
| [UB#2](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/3?page=1&test=1) | **Subtractions between pointers that may not point to the same allocated block** in function 'calculate_crc_soft' in file 'librhash/crc32.c' line 38. | `(msg - (unsigned char*)0))` | [FIXED](https://github.com/jakub-zwolakowski/RHash/commit/df938dc2ca16685217445901543f297fd5aafc34) |
| [UB#3](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/4?page=1&test=1) | **Subtractions between pointers that may not point to the same allocated block** in function 'rhash_swap_copy_str_to_u32' in file 'librhash/byte_order.c' line 77. | `(char*)ptr - (char*)0` | [FIXED](https://github.com/jakub-zwolakowski/RHash/commit/48babd47f32df6cb249c5da669836e2c49bbbc98) |
| [UB#4](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/5?page=1&test=5) | **Invalid index in address-of operator** in function 'rhash_init_multi' in file 'librhash/rhash.c' line 122. | flexible array member | [FIXED](https://github.com/jakub-zwolakowski/RHash/commit/370ece5154250eaccc37bbdf85202d5c9635b928) |
| [UB#5](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/6?page=1&test=5) | **Subtractions between pointers that may not point to the same allocated block** in function 'rhash_gost12_update' in file 'librhash/gost12.c' line 820. | `(const char*)(p) - (const char*)0` | [FIXED](https://github.com/jakub-zwolakowski/RHash/commit/84e25e31f4665d895add860d4b407e22ac9ccbfe) |
| [UB#6](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/7?page=1&test=5) | **Uninitialized memory** in function 'rhash_md5_final' in file 'librhash/md5.c' line 216. | uninitialized memory access | [WORKAROUND](https://github.com/jakub-zwolakowski/RHash/commit/59e1a18893cdbb9c1731e459175c86217d521acc) |
| [UB#7](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/8?page=1&test=9) | **Invalid pointer arithmetic** in function 'get_basename' in file 'file.c' line 65. | computing a negative pointer | [FIXED](https://github.com/jakub-zwolakowski/RHash/commit/a7cd043c7089f0f28c015acbe8553348785a8c3a) |
| [UB#8](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/9?page=3&test=41) | **Invalid pointer arithmetic** in function 'bt_bencode_pieces' in file 'librhash/torrent.c' line 365. | pointer arithmetic | [FIXED](https://github.com/jakub-zwolakowski/RHash/commit/4f81620eee37e4598679f99e882b36b767caaf63) |
| [UB#9](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/10?page=5&test=89) | **Invalid memory access** in function 'rhash_tiger_update' in file 'librhash/tiger.c' line 170. | invalid pointer as `memcpy` argument | [FIXED](https://github.com/jakub-zwolakowski/RHash/commit/cce4368e77031636010f4a6d58553cdb4fe1f0b8) |
| [Failed tests](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/11?page=3&test=43,44)| Test case `test_all_known_strings` on big-endian machdeps fails at `EDON-R256` sub-case. | endianness handling? | NOT FIXED |

#### UBs
-   **`ptr - 0`: UB#1, UB#2, UB#3, UB#5**  
    Behavior of such subtractions actually undefined.  
    The standard-compliant way to do this is with a cast to `uintptr_t`.
-   **Flexible Array Member: UB#4**  
    This way of handling an array at the end of a struct is not standard-compliant, as in this case accesses to indices larger than 0 are, in fact, out of bound.  
    The standard-compliant way is using a Flexible Array Member.
-   **Uninitialized memory: UB#6**  
    There is uninitialized memory access.  
    I'm not sure what exactly is supposed to initialized this memory location, so as a workaround I've initialized it to zero directly after the allocation.
-   **Minor pointer issues: UB#7, UB#8, UB#9**  
    Some pointer arithmetic is slightly off (i.e. not standard-compliant) in two cases.  
    The third case is an invalid pointer passed to `memcpy` function (even if the size parameter is zero in all such cases it is still an UB to pass an invalid pointer).
    Solutions to these are pretty trivial.
    
#### Failed tests

[Tests **43** and **44**](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/11?page=3&test=43,44) have no UB, but they fail (the results are wrong). Their little-endian versions ([tests **41** and **42**](https://ci.trust-in-soft.com/projects/jakub-zwolakowski/RHash/11?page=3&test=41,42)) succeed.

Upon closer inspection (Analyzer Log) we can see that these tests print:
```
failed: EDON-R256 ...
```
This is one of the last cases in `test_all_known_strings`, all the previous ones pass.

There are two options why this happens:
- either I've misconfigured TIS-CI and it computes something with the wrong endianness in this particular case,
- or there is an actual functional bug in the code which happens only when computing this particular case on a big-endian architecture.

As I did my best to make sure that the TIS-CI config is right (and managed to make all the other tests pass both on little-endian and big-endian architectures) I think that the second option may be worth investigating. Well, depending on how confident you are in your continuous testing for big-endian.

**Comment by rhash** [comment]
Hello, 
thank you for the investigation. I will check you results, when I have time.

For now I've re-tested `test_all_known_strings()` on Big-Endian platforms, but could not reproduce the EDON-R problem. I've used cross-building by powerpc-linux-gnu-gcc and gcc-powerpc64-linux-gnu toolchains and tested under qemu. Please try to reproduce the test failure on any platform using unmodified librhash sources.

**Comment by jakub-zwolakowski** [comment]
Hi @rhash,

Thank you for your feedback! And especially for retesting the EDON-R case! As you say that your cross-building test works well, I will recheck everything on my side to pinpoint what is going on here.

Would you like me to make separate PRs for all these issues that I found? It may be more convenient to discuss them one by one and decide if you want to merge my fixes or do something else.

**Comment by rhash** [comment]
Hello,
I see that similar UB# 1,UB#2,UB#3,UB#5 should be combined into one PR,
and UB#4, UB#6, UB#7, UB#8, UB#9 should be discussed in separate PRs.

**Comment by jakub-zwolakowski** [comment]
Hi again!

I've created PRs as you asked (I agree with the grouping of UBs in PRs). I'm pretty confident that 4 of them are mergable directly:
- https://github.com/rhash/RHash/pull/150
- https://github.com/rhash/RHash/pull/151
- https://github.com/rhash/RHash/pull/152
- https://github.com/rhash/RHash/pull/153

And these two require some insight:
- https://github.com/rhash/RHash/pull/154
- https://github.com/rhash/RHash/pull/155

# About EDON-R256

After further investigation I've found the problem in the config on my side - some badly defined architecture-related macros which affected an `#if` in `edonr.c`. It's corrected now! So I can confirm that all passes well both on little an big-endian.

Thanks for your feedback! :)

**Comment by rhash** [comment]
All created PRs were processed.
