### ISSUE TITLE
RHash Failed to verify checksum

### ISSUE THREAD

**Issue by ykhoe** [rhash/RHash#148]
I produced the checksum file command:
rhash.exe --md5 "grandes roussieres 1.pm" > "grandes roussieres 1.md5"

The contents of the md5 is
1b564cada5c519216d21a6c57f16fb1f  grandes roussieres 1.pm

![image](https://user-images.githubusercontent.com/81351293/112436837-2cfce180-8d81-11eb-8293-49da4c65a794.png)
It will always fail if I use this filename. It will be working fine if I change the filename to for example: "House test test".

If I regenerate the checksum file by renaming it  as below:
rhash.exe --md5 "grande roussieres 1.pm" > "grande roussieres 1.md5"
It works fine.

**Comment by rhash** [comment]
Thank you for the bug report! The program erroneously interpreted the string
`"1b564cada5c519216d21a6c57f16fb1f grandes"` as `MD5` and `BASE32(CRC32)` of "roussieres 1.pm".

The bug is now fixed by 9105d546ea636b994337b71c976e1606306b1989.
