### ISSUE TITLE
blake2 implementation is wrong

### ISSUE THREAD

**Issue by tankf33der** [rhash/RHash#158]
While tested newly added (~4 monthes ago) blake2 implementations to this library I found it starting generate wrong results if input became larger than 32 bytes for blake2s and larger than 64 bytes for blake2b, this is a very suspicious and must be checked.

I bet you would fail on official test vectors If you have key support anyway :).

Do not hesitate use @LoupVaillant Monocypher library to check my findings.

**Comment by rhash** [comment]
Thanks for the bug report, I'll check it.

**Comment by rhash** [comment]
I've tested RHash implementation on x86-64 Linux against [official test vectors](https://github.com/BLAKE2/BLAKE2/blob/master/testvectors/blake2-kat.json) (256 vectors for blake2s and 256 vectors for blake2b).
 All tests have succeeded.

**Comment by tankf33der** [comment]
It was a silly tyop in my own test suite. Rhash is ok.

Thank you for patience.
