### ISSUE TITLE
recursive not working on updating existing checksum file?

### ISSUE THREAD

**Issue by rainforest1155** [rhash/RHash#16]
I have about 2TB of data in OpenMediaVault on a BeagleBoneBlack. I was thinking of using RHash to periodically generate an MD5 file to verify the integrity of the files with a backup. Due to the huge data set and the slow USB speed provided by the BBB, it'll likely take a few days for all data to be hashed. 

That's where the --update parameter of RHash was to supposed to help in case the process gets somehow interrupted. However, it doesn't appear as if the update actually works recursively. It only seems to be picking up files in the same folder the checksum file is located in. Here's the command I tried:
rhash --md5 -ru test.md5

test.md5 is located in the folder that contains all the folders / files that RHash is supposed to generate checksums for. I've also tried adding -vv but it doesn't provide any clue on what may be the problem.

Is there really not an option to have RHash recursively perform an update? Will this be added in a future update? 

I'm using Debian Wheezy, which is still on RHash 1.2.9-8, but even installing the Jessie release version 1.3.3-1 doesn't seem to make any difference.

**Comment by rhash** [comment]
-r option makes rhash to recursively search all directories specified on command line (you ommited them), then rhash will run in --update mode on each found file. Processed files can be limited by extension, using --crc-accept=".md5".

The update mode expects to add to the md5-file all the files from the same directory.

The only supported way for the -ru options is to place the *.md5 file in each directory.

**Comment by Hashnoob** [comment]
Not to bring up an old issue but I'm having the same problem and would like to make sure I read your reply right. Is this normal or did I miss something.

Issue: Using -r with -u will only find new files in the starting directory.

This is working great and finds all files as expected.
Creating: "rhash -r * -M --sfv -o hash.md5"

When trying to update hash.md5 rhash only finds files in the starting directory.
Updating: "rhash -r  -u hash.md5 -M --sfv"

Any help would be appreciated. :)
