### ISSUE TITLE
Rename files to their checksum

### ISSUE THREAD

**Issue by 1024mb** [rhash/RHash#162]
Currently we can append the checksum to the filename, could you add another param to rename the files to only their checksum?

**Comment by rhash** [comment]
This feature is too specific to implement it in RHash itself.

Use the following python script _rename_to_crc32.py_ to do this
~~~python
#!/usr/bin/env python3
"""rename_to_crc32.py - rename files to their checksums."""

import os
import sys
import rhash

# Id of the hash function to calculate the checksum or message digest.
_HASH_ID = rhash.CRC32


def rename_to_checksum(path, hash_id):
    """Rename file to its checksum or message digest."""
    message_digest = rhash.hash_file(path, hash_id)
    new_path = os.path.join(os.path.dirname(path), message_digest)
    print("{} -> {}".format(path, new_path))
    os.rename(path, new_path)


for filepath in sys.argv[1:]:
    rename_to_checksum(filepath, _HASH_ID)
~~~

To run the script you must first install [rhash](https://test.pypi.org/project/rhash-Rhash/) module:
~~~sh
pip install rhash-Rhash
~~~

Optionally you can change the _HASH_ID constant in the script to the id of hash function you need.

Run the script as
~~~sh
rename_to_crc32.py FILES_TO_RENAME...
~~~


To rename files in a directory tree (or several trees) use the _find_ command
~~~sh
find DIRECTORIES... -type f -exec rename_to_crc32.py '{}' ';'
~~~

**Comment by 1024mb** [comment]
Thank you!
