### ISSUE TITLE
Empty .sfv file allowed when checking

### ISSUE THREAD

**Issue by nadiaholmquist** [rhash/RHash#164]
```
$ echo "" > test.sfv
$ rhash -c test.sfv

--( Verifying test.sfv )--------------------------------------------------------
--------------------------------------------------------------------------------
Everything OK
```
RHash should show some kind of warning for this case, as this makes it possible to trick the user into thinking everything is okay if they don't think to verify the contents of the .sfv file, or only checked it against a provided hash.

**Comment by rhash** [comment]
The FR is implemented by 3e3c81c7b5ca80a2c8a03daf3733cc42e9532b5a and got into release v1.4.2.

~~~sh
echo | rhash -c -

--( Verifying (stdin) )---------------------------------------------------------
--------------------------------------------------------------------------------
Nothing to verify
~~~

**Comment by Perkolator** [comment]
Really late to this (finally managed to build a newer version for the first time and finally update from the very old version 1.3.9 offered by package manager).

Shouldn't the "Nothing to verify" be an error? If there's a hash file, but there's nothing to verify in it, I would see it as an error.

I have a problem when bash `"$?"` returns `0` for "Nothing to verify".

**Comment by rhash** [comment]
It was originally designed to return `1` only if a message digest has mismatched, but not on empty file.

I've checked now that this disagrees with md5sum/sha1sum behavior in Ubuntu:
~~~sh
$ sha1sum -c /dev/null || echo "FAIL (res=$?)"
sha1sum: /dev/null: no properly formatted SHA1 checksum lines found
FAIL (res=1)
~~~

**Comment by Perkolator** [comment]
Excellent. Eagerly waiting for the new version that fixes this. :)
