### ISSUE TITLE
librhash/byte_order.c:  use of undeclared variable v (should be x)

### ISSUE THREAD

**Issue by stopped** [rhash/RHash#17]
line 59:

    -     return (unsigned)bit_pos[((uint32_t)((v & -v) * 0x077CB531U)) >> 27]; 
    +     return (unsigned)bit_pos[((uint32_t)((x & -x) * 0x077CB531U)) >> 27];

**Comment by rhash** [comment]
You are right. Thank you! =)

**Comment by rhash** [comment]
The patch is applied in the commit e566922cd3dbc0f719c6e9ba1881c3c60ca107b2
