### ISSUE TITLE
the -e option does not respect --lowercase

### ISSUE THREAD

**Issue by martoko** [rhash/RHash#175]
I would expect the --lowercase switch to also apply when embedding hashes, not just printing it.

Currently it is always uppercase when embedding.

**Comment by rhash** [comment]
It is interesting feature request. Accepted.

**Comment by rhash** [comment]
Implemented by 5c9004d8e0c079ddac2c4f9f7175f75f383a5ac3.

**Comment by rhash** [comment]
The feature got included into [RHash v1.4.3](https://github.com/rhash/RHash/releases/tag/v1.4.3) release.
