### ISSUE TITLE
Fatal error when building java bindings

### ISSUE THREAD

**Issue by marcincharezinski** [rhash/RHash#176]
Hi

I was trying to make usage of the java binding, but could not build it properly.

cc -g -O2  -fPIC   -c bindings.c -o bindings.o
bindings.c:18:10: fatal error: 'rhash.h' file not found

**Comment by rhash** [comment]
You must install LibRHash library into you system (it is recommended to use system package manager for this), so the rhash.h must be found in the system includes directory and librhash shared library (*.so or *.dll, e.t.c.) must be in the system libraries directory.

Alternatively you can pass includes and libraries directory paths to the "cc" compiler using environment variables or by modifying makefiles.

**Comment by marcincharezinski** [comment]
Thank you @rhash for the replay. I use macos and after I installed rhash using brew still the problem occurs.

**Comment by rhash** [comment]
I suppose you have installed rhash utility with librhash.0.dylib shared library. But in order to compile java bindings, you need also development files. Usually you should install some librhash-dev package, but I'm not sure if brew has one.

Try to compile and install librhash, from sources, before compiling java bindings.

**Comment by marcincharezinski** [comment]
I'm not sure what does it mean "compile and install librhash from sources" but what I did was:

1. ./configure && make && make install
2. make test test-lib (All sums are working properly!)
3.  cd ./bindings/java/  && make
```
mkdir -p dist
ln -fs rhash-1.4.2.jar dist/rhash.jar
/Library/Developer/CommandLineTools/usr/bin/make -C native
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
cc -g -O2  -fPIC   -c bindings.c -o bindings.o
bindings.c:18:10: fatal error: 'rhash.h' file not found
#include <rhash.h>
         ^~~~~~~~~
1 error generated.
make[1]: *** [bindings.o] Error 1
make: *** [dist/librhash-jni.so] Error 2
```

**Comment by rhash** [comment]
You shall change the first step to `./configure && make lib-static install-lib-static`
since `make install` installs only rhash utility, without development files.

**Comment by marcincharezinski** [comment]
This time error is dofferent after following your first step.

```
mkdir -p dist
ln -fs rhash-1.4.2.jar dist/rhash.jar
/Library/Developer/CommandLineTools/usr/bin/make -C native
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
cc -g -O2  -fPIC   -c bindings.c -o bindings.o
In file included from bindings.c:33:
./bindings.h:2:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^~~~~~~
1 error generated.
make[1]: *** [bindings.o] Error 1
make: *** [dist/librhash-jni.so] Error 2
```

**Comment by rhash** [comment]
The _jni.h_ header is used to compile JNI extensions. Something is wrong with your Java environment setup.

* Check if the _JDK_HOME_ environment variable is set correctly.
* Look for the jni.h header file, it should be at `$(JDK_HOME)/include`.
* If the jni.h header is located in a non standard place, then pass the include directory to the make command as: 
`make JNI_CFLAGS="-I<JNI_HEADER_DIRECTORY>"`
* If the above does not help, then [google](https://www.google.com/search?q=%22fatal+error:+%27jni.h%27+file+not+found%22+site:stackoverflow.com&hl=en) for solution.
