### ISSUE TITLE
APPCRASH: rhash --torrent -

### ISSUE THREAD

**Issue by ivan386** [rhash/RHash#178]
rhash-1.4.2-win64

>rhash -V
RHash v1.4.2

Command:
```rhash --torrent -```

When i run this command program crush. Option ```--bt-batch="file_name.torrent"``` fix this problem.

**Comment by rhash** [comment]
Thanks for reporting the bug!

Fixed by 684706ca236b006fb0d58308ebd4f860587ba68d.

**Comment by rhash** [comment]
Fix included into [RHash v1.4.3](https://github.com/rhash/RHash/releases/tag/v1.4.3).
