### ISSUE TITLE
New Output Format Options

### ISSUE THREAD

**Issue by i2324561w2** [rhash/RHash#182]
I think it would be good to have a way to insert automatically on every text file the date you created the hashes on (on a backup the creation date of said text file would change), plus the exact command you passed, and maybe the total_time+average_MBps (basically the last line of the output on Command Prompt).
Thanks for considering this.

**Comment by rhash** [comment]
The time is already inserted into hash-file in the `--sfv` format. RHash allows to use SFV format with any hash function. Regrettably the date is not changed on `--update` operation.

The Feature Request to write so much extra information is too specific. I think it would be not a popular feature, but adding new options will complicate the RHash codebase and the man page. So I reject this FR.

You should write a wrapper shell script to implement the behavior you've requested.
