### ISSUE TITLE
Add output of ed2k complete hashset

### ISSUE THREAD

**Issue by rowaasr13** [rhash/RHash#183]
It is already calculated as part of calculating of ed2k root hash, but there are no option to output it. eMule will output it as `p=` part of the link if you when you select "eD2K Links..." from right-click menu and set "Add complete hashset" checkmark here.

Here's an example of link for randomly selected open source software portable file:
Source file: https://www.fosshub.com/MKVToolNix.html?dwl=mkvtoolnix-64-bit-63.0.0.7z
ed2k link with hashset: ed2k://|file|mkvtoolnix-64-bit-63.0.0.7z|22411096|DE41B7EBACFD27F3AB5DDEB8E6ADF45E|***p=34B4D1EFB1509FD45ED9441B6B84A402:92D1EA13F97E3AC48BA0392837B6A1D2:7DC5E52438DA9A4F246BCEC041552E6E***|h=MG5CIGCFJODYPPFLH4GJYY7AH6OTQKEH|/

**Comment by rhash** [comment]
The project is done in my free time, which is very limited, and the project is overloaded by feature requests. So I must reject some FR, like this one.

Feel free to fork the project, or at least write a PR for LibRHash to retrieve "complete hashset" from ED2K. See how extra information is retrieved from torrent (BTIH) algorithm. After updating LibRHash, you can use it from Python or other scripting language to write a simple script for your needs.

**Comment by pataquets** [comment]
@rhash As I'm guessing you're OK with the feature scope but not up to the task coding yourself (which is perfectly understandable), may I suggest to keep the issue open as valid and label it with as "pr-welcome", in case anyone feels like it scratching their own itch and picks it up? (if the PR could be acceptable)
Notice: I understand you wanting to keep the issue list tidy, too. Just trying to also reflect better your intentions. In the end, it's your issue queue and your show, not anyone else's. I can be only thankful for sharing your work.
