### ISSUE TITLE
EDON-R  -c is very slow

### ISSUE THREAD

**Issue by satori80** [rhash/RHash#184]
rhash --edonr256 --skip-ok -c *.sum runs at < 20 MB/s in Win, unless --bsd is used during creation.

**Comment by rhash** [comment]
The bug is independent on OS.

RHash v1.4.1-1.4.2 incorrectly ignores the hash options passed by the command line, and tries to detect hash function by hash file extension. As a workaround, pass the `--no-detect-by-ext` option.

**Comment by rhash** [comment]
Fixed by 79a1a0b3d267893c40ac31192b20e20969a3a79c.

**Comment by rhash** [comment]
Fix included into [RHash v1.4.3](https://github.com/rhash/RHash/releases/tag/v1.4.3).
