### ISSUE TITLE
Support for hash file format with * before filename

### ISSUE THREAD

**Issue by 1024mb** [rhash/RHash#187]
Please, add support for this file format:

```
8549B5858546E6ED0BD76E409E30812E *WinPE10_8_Sergei_Strelec_x86_x64_2021.10.15_English.iso
```

I've been stumbling with a lot of checksum files like that: a `*` before the filename, but RHash thinks the `*` belongs to the filename and thus says it can't find such file. One thing that could work in this case (as Unix does allow for `*` in the filename) is first checking if a file with a `*` at the start exist if not then it just ignores the `*`.

**Comment by rhash** [comment]
Duplicate of #177.

**Comment by 1024mb** [comment]
Woops, sorry. Didn't find it and is even fixed already. Thank you.
