### ISSUE TITLE
ar: archive librhash.a not found SunOS

### ISSUE THREAD

**Issue by mimir1980** [rhash/RHash#188]
ar cqs librhash.a algorithms.o byte_order.o plug_openssl.o rhash.o rhash_timing.o rhash_torrent.o aich.o blake2b.o blake2s.o crc32.o ed2k.o edonr.o hex.o md4.o md5.o sha1.o sha256.o sha512.o sha3.o ripemd-160.o gost12.o gost94.o has160.o snefru.o tiger.o tiger_sbox.o tth.o torrent.o util.o whirlpool.o whirlpool_sbox.o
ar: archive librhash.a not found
*** Error code 1
make: Fatal error: Command failed for target `librhash.a'

When I try to build with shared library configure option enabled. I of course get a successful *.so

ln -s librhash.so.0 librhash.so
gcc -DOPENSSL_RUNTIME -O2 -DNDEBUG -pipe -ffunction-sections -fdata-sections -fomit-frame-pointer -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations -Wdeclaration-after-statement  -fpic -DRHASH_XVERSION=0x01040200 algorithms.c byte_order.c plug_openssl.c rhash.c rhash_timing.c rhash_torrent.c aich.c blake2b.c blake2s.c crc32.c ed2k.c edonr.c hex.c md4.c md5.c sha1.c sha256.c sha512.c sha3.c ripemd-160.c gost12.c gost94.c has160.c snefru.c tiger.c tiger_sbox.c tth.c torrent.c util.c whirlpool.c whirlpool_sbox.c   -shared -Wl,-soname,librhash.so.0 -o librhash.so.0
gcc calc_sums.o hash_print.o common_func.o hash_update.o file.o file_mask.o file_set.o find_file.o hash_check.o output.o parse_cmdline.o rhash_main.o win_utils.o librhash/librhash.so.0   -o rhash

**Comment by mimir1980** [comment]
# -------- Generated by configure -----------

DESTDIR =
INCDIR  = $(DESTDIR)/export/home/mimir/illumospkgsrc//include
LIBDIR  = $(DESTDIR)/export/home/mimir/illumospkgsrc//lib
SO_DIR  = $(DESTDIR)/export/home/mimir/illumospkgsrc//lib

AR      = ar
CC      = gcc
INSTALL = install

LIBRHASH_STATIC  = librhash.a
LIBRHASH_SHARED  = librhash.so.0
LIBRHASH_SOLINK  = librhash.so
LIBRHASH_DEF     = librhash.def
LIBRHASH_IMPLIB  = librhash.so.0.a
EXPORTS_FILE     = exports.sym
RM_FILES         = librhash.so
BUILD_TYPE       = shared
EXEC_EXT         =
LEGACY_HEADERS   = rhash_timing.h

EXPORTS_TARGET   =
BUILD_TARGETS    = librhash.so.0
TEST_TARGETS     = test-shared
SOLINK_TARGET    = librhash.so
EXTRA_INSTALL_LIBSHARED   =
EXTRA_UNINSTALL_LIBSHARED =

OPTFLAGS    = -O2 -DNDEBUG -pipe -ffunction-sections -fdata-sections -fomit-frame-pointer
OPTLDFLAGS  =
WARN_CFLAGS = -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations -Wdeclaration-after-statement
ADDCFLAGS   =
ADDLDFLAGS  =
CFLAGS  = -DUSE_OPENSSL $(OPTFLAGS) $(WARN_CFLAGS) $(ADDCFLAGS)
LDFLAGS = $(OPTLDFLAGS) $(ADDLDFLAGS)
SHARED_CFLAGS  = $(CFLAGS) -fpic
SHARED_LDFLAGS = $(LDFLAGS) -lcrypto -shared -Wl,-soname,$(LIBRHASH_SHARED)
VERSION_CFLAGS = -DRHASH_XVERSION=0x01040200
BIN_STATIC_LDFLAGS = $(LDFLAGS) -lcrypto

**Comment by rhash** [comment]
@mimir1980, thank you for reporting this bug!

Broken building of the LibRHash static library is repaired by commit 2177ea85e0851bd06092ffb238bce1198d682c8e.

Please re-test building from the master branch.

**Comment by rhash** [comment]
Fix included into [RHash v1.4.3](https://github.com/rhash/RHash/releases/tag/v1.4.3).
