### ISSUE TITLE
Option to output relative path 

### ISSUE THREAD

**Issue by 1024mb** [rhash/RHash#189]
Currently using the default or using `%p` as output format outputs the full path of the file, could you please add an option to output the relative path instead?
This is more useful when hashing files inside subdirectories as if we use `%f` only the file names are stored.

So if we have something like this:

```
C:\Test¬
	  \dir 1¬
		  file a.txt
		  file b.txt
	  \dir 2¬
		  file c.txt
		  file d.txt
	  file e.txt
```

And we use `--printf="%{Sha3-512} %rp%f\n"` (assuming `%rp` is the new option) we get:

```
XXXXXXXXXXX dir 1\file a.txt
XXXXXXXXXXX dir 1\file b.txt
XXXXXXXXXXX dir 2\file c.txt
XXXXXXXXXXX dir 2\file d.txt
XXXXXXXXXXX file e.txt
```

**Comment by rhash** [comment]
I can't reproduce the bug. Please provide more info.

The option "%p" already outputs **relative file paths** if you passed a relative directory path to RHash, and it outputs absolute filepaths **only** if absolute directory path has been passed by command line:
~~~bat
C:\Test>rhash -r --printf="%{md5} %p\n" .
d41d8cd98f00b204e9800998ecf8427e file e.txt
d41d8cd98f00b204e9800998ecf8427e dir 1\file a.txt
d41d8cd98f00b204e9800998ecf8427e dir 1\file b.txt
d41d8cd98f00b204e9800998ecf8427e dir 2\file c.txt
d41d8cd98f00b204e9800998ecf8427e dir 2\file d.txt

C:\Test>rhash -V
RHash v1.4.2
~~~

**Comment by 1024mb** [comment]
Thanks and sorry for replying so late. You are right, my script was giving the full path and that's why I was getting the same in the checksum file.
