### ISSUE TITLE
Feature REQ: Add option to also calculate/display file size

### ISSUE THREAD

**Issue by Obiwantje** [rhash/RHash#195]
In many cases it'd be handy to also show the size in bytes for the file processed - can this be added?

**Comment by rhash** [comment]
It is already supported by the `--printf` option (see [manpage](http://rhash.sf.net/manpage.php)), which allows to customize output format.

The size is also printed by options `--ed2k-link` and `--magnet`, moreover, hash files in these two formats can also be verified by RHash. There are no plans to support new hash file formats, so a separate option you've requested also will not be supported.

You can write Batch or Shell script to make RHash print file sizes using the `--printf` option.
