### ISSUE TITLE
Command "--update" doesn't give "Total" stats

### ISSUE THREAD

**Issue by i2324561w2** [rhash/RHash#196]
When I compute the hash of a folder, at the end it says the total seconds and MBps, but this doesn't happen when using the "update" command. Am I doing something wrong, or it's not implemented (in this case I hope you will add it, please)?

**Comment by rhash** [comment]
Thank you for reporting the bug.

The bug is fixed by commit ee4e6115cdc1b667665ed2e86721dbe95b01641c.

**Comment by rhash** [comment]
Fix included into [RHash v1.4.3](https://github.com/rhash/RHash/releases/tag/v1.4.3).
