### ISSUE TITLE
Cannot read files with backslashes in their names

### ISSUE THREAD

**Issue by systwi-again** [rhash/RHash#201]
The title basically says it all.

    $ rhash --simple 'foo\bar'
    RHash: foo/bar: No such file or directory

`rhash` (version 1.4.2) wants to interpret backslashes as forward slashes, which makes sense on Windows systems where the two can usually be used synonymously without issue. I'm using Arch (btw), where backslashes are permitted in filenames.

My theorized solution is to add a switch to `rhash` that disables this feature and treats `\` and `/` as their own characters (backslash and path delimiter) both when writing and reading hash files (output). Maybe even using backslash escapes for offending characters, like GNU coreutils' `md5sum`, would be a nice workaround.

I would very much appreciate if this bug could be rectified.

Best regards.

**Comment by rhash** [comment]
This issue should be solved by implementing the feature #97, that means:
> using backslash escapes for offending characters, like GNU coreutils' md5sum
