### ISSUE TITLE
add git blob hash algo

### ISSUE THREAD

**Issue by milahu** [rhash/RHash#203]
```
$ gitblobhash() { ( printf 'blob %i\0' $(stat -c%s "$1"); cat "$1"; ) | sha1sum - | cut -c1-40; }

$ gitblobhash tools-8.0.jar && git hash-object tools-8.0.jar
8cbe563d5664f2a91a94743300abe5a7a6c2bf4f
8cbe563d5664f2a91a94743300abe5a7a6c2bf4f
```

**Comment by rhash** [comment]
Git glob hash is a rare algorithm. So the feature will hardly be used,

Also, Git glob algorithm requires the file size to be known in advance, so it cannot be implemented for a file passed to RHash as standard input (e.g. `rhash --sha1 -`).

I have already hands full with more popular algorithms like BLAKE3 and xxhash. So I reject this feature.
