### ISSUE TITLE
Format parameter for dirname

### ISSUE THREAD

**Issue by forthrin** [rhash/RHash#216]
Thanks for a very useful utility!

Could you add a format parameter for file dirname?

I was expecting -p "%p" to contain the dirname only, so one is free to print dirname and filename jointly or separately.

```
%p/%f
%p\t%f
```

A format parameter for file extension would also be very nice to have.

**Comment by rhash** [comment]
The '%d' directive for dirname is now supported by commit b41c17cff7e79c4ba855d76a3f75c07dbfe0a580.

**Comment by forthrin** [comment]
Works for me as expected. Very nice! Thank you! Please post a comment here if you decide to include a parameter for:

- File extension

This would be very beneficial and time saving! Thanks again!
