### ISSUE TITLE
Error log is created but is empty, no error added to log

### ISSUE THREAD

**Issue by benpollinger** [rhash/RHash#218]
Thanks for rhash, it's very useful. I'm using version 1.4.1 on Debian 11 armhf

I was testing out the --log option to capture errors, but when I deliberately changed the last digit of a CRC in a rhash output file, the error was detected but not logged. The log file was empty. See below:

```
ben@odroidhc2:~$ rhash -c docker-compose.yml.rhash --log=rhashcheck.log
--( Verifying docker-compose.yml.rhash )----------------------------------------
docker-compose.yml                                  ERR
--------------------------------------------------------------------------------
Errors Occurred: Errors:1   Miss:0   Success:0   Total:1
ben@odroidhc2:~$ cat rhashcheck.log
ben@odroidhc2:~$ ls -l rhashcheck.log
-rw-r--r-- 1 ben users 0 Dec  2 22:37 rhashcheck.log
```

**Comment by rhash** [comment]
The verification error above is considered normal operation of the program and it is reported to the standart output, which can be redirected by `--output`.

The `--log` option catches errors like wrong program option or problem with reading or parsing a hash file. A log file specified by the `--log` or `--output` option is opened for writing at the start of the program, so it is always created, even if no data will be written.

Try running `rhash --brief --skip-ok -c <HASH_FILE> --output=<OUTPUT_FILE>`, then the `<OUTPUT_FILE>` will contain the verification errors and the total verification result.

**Comment by benpollinger** [comment]
I see, thanks for the reply and clarification.

This time I got an error when using `--brief` but OK without it:

```
ben@odroidhc2:~$ rhash --brief --skip-ok -c docker-compose.yml.rhash --output=rhashcheck.log
RHash: unknown option: --brief
ben@odroidhc2:~$ ls rhashcheck.log
ls: cannot access 'rhashcheck.log': No such file or directory
ben@odroidhc2:~$ rhash --skip-ok -c docker-compose.yml.rhash --output=rhashcheck.log
ben@odroidhc2:~$ cat rhashcheck.log
--( Verifying docker-compose.yml.rhash )----------------------------------------
docker-compose.yml                                  ERR
--------------------------------------------------------------------------------
Errors Occurred: Errors:1   Miss:0   Success:0   Total:1
```

**Comment by rhash** [comment]
Check [changelog](https://rhash.sourceforge.net/changelog.php) to find out which RHash version supports the options you need.

**Comment by benpollinger** [comment]
Ah I see, my Debian repo only has 1.4.1-2 

Thanks again!
