### ISSUE TITLE
Add configure option to build non-static executable only statically linked with librhash.a

### ISSUE THREAD

**Issue by lvd2** [rhash/RHash#220]
Now `--enable-static` option results in a fully static executable, i.e. with libc.a and libcrypto.a parts inside and of enormous size (>1 Mb). Linking without `-static` option but still with `librhash/librhash.a` would include only librhash objects while keeping libc and libcrypto dynamic.

So this issue is about adding a new option to configure script to do exactly that.

**Comment by rhash** [comment]
The option _--enable-static=librhash_ has been supported by commits: 851d459dbf530b7e1f64d4140d3c314ad054c70a, 3f5dfd7af8e181bc4792f8db0afde799f4c8a2e4.

**Comment by rhash** [comment]
Implemented in RHash v1.4.4.
