### ISSUE TITLE
%d, documentation

### ISSUE THREAD

**Issue by therube** [rhash/RHash#230]
%d,
should be documented.

**Comment by therube** [comment]
(I've yet to look to see what %d does... but...)

Food for thought... Should %p / %d including the trailing path separator?

`c:/tmp/ vs. c:/tmp`

**Comment by rhash** [comment]
The option '%d' has been added by the commit b41c17cff7e79c4ba855d76a3f75c07dbfe0a580, which will be included into the upcoming version 1.4.4.
The [manual page](https://rhash.sourceforge.net/manpage.php) on the project website will be updated after this release.
