### ISSUE TITLE
slash / vs. backslash \

### ISSUE THREAD

**Issue by therube** [rhash/RHash#233]
slash / vs. backslash \

some ;-) prefer / over \ (even on Windows)
& while it seems you can use / with rhash (or even intermix / & \ ) (as a directory separator)
output results can be odd, in some cases, with any input \ resulting in an output of /\

it would be nice if slashes were always normalized on output (to the OS standard)

rhash -H -r ./tmp/rhash/*
-> <hash> tmp/rhash/\rhash-doc.html

```
T:\K-ORSAIR\RHash-1.4.3-win64>rhash -H -r ./tmp\rhash/*
73d2862f0442334f2628ceacd37128db556361e5  tmp\rhash/\doc

T:\K-ORSAIR\RHash-1.4.3-win64>rhash -H -r ./tmp/rhash/*
73d2862f0442334f2628ceacd37128db556361e5  tmp/rhash/\doc

T:\K-ORSAIR\RHash-1.4.3-win64>rhash -H -r ./tmp/rhash\*
73d2862f0442334f2628ceacd37128db556361e5  tmp/rhash\doc
```
note the various styled outputs depending on the input path separator(s)

**Comment by rhash** [comment]
Hello, thank you for reporting the bug about the trailing slash not being removed on Windows console when a path ends with asterisk symbol (*).

> it would be nice if slashes were always normalized on output (to the OS standard)

There is --path-separator=<SEPARATOR> option for this. By default the path provided by user is left as is. Modifying this behavior is bad for scripting, it would affect some scripts, which run rhash and then search the passed path in the output.
