### ISSUE TITLE
[EXPIRED] xxHash

### ISSUE THREAD

**Issue by sergeevabc** [rhash/RHash#26]
Пожалуйста, добавьте поддержку алгоритма [xxHash][1] — это шаг в будущее, доступное в [202](http://create.stephan-brumme.com/xxhash/) строчках кода. Судя по [тестам](http://aras-p.info/blog/2016/08/09/More-Hash-Function-Tests/), работает шустрее CRC32, что пригодится при подсчёте контрольных сумм *.iso, *.mkv, БД и тому подобных больших файлов. Сегодня это есть в [HashOnClick][2], но, увы, за $$$.

[1]: http://cyan4973.github.io/xxHash/
[2]: https://www.2brightsparks.com/onclick/help/welcomehashonclick.htm

**Comment by sergeevabc** [comment]
Может быть, всё-таки добавим?

**Comment by data-man** [comment]
> Судя по тестам, работает шустрее CRC32

[MetroHash](https://github.com/jandrewrogers/MetroHash) ещё быстрее :-)
[Есть](https://github.com/jedisct1/metrohash-c) реализация на C (64-bit, 128-bit, и 128-bit с использованием инструкции CRC)
