### ISSUE TITLE
PyPI is outdated

### ISSUE THREAD

**Issue by todeskurve** [rhash/RHash#266]
[pypi.org/RHash](https://pypi.org/project/RHash/)

this is such a great project, please make it available on PyPI so aspiring python programmers can make us of it :-)

after some trouble i saw that the version on PyPI is outdated and perhaps broken (dll isn't found)

the python binding there will not accept multiple hashes like it is noted in the documentation here

finding the right spot for the .dll was not easy either (i just used a full path to 'fix' this for me)

i first stumbled using PyCharm with .venv but normal command line installation with pip didn't work either

i really hope a current wheel on PyPI would fix these issues so other won't run into those :-)

**Comment by rhash** [comment]
Try `pip install rhash-Rhash`.

If the installed package doesn't work, then describe:
* OS
* version of installed librhash
* location of librhash library

**Comment by rhash** [comment]
@todeskurve we do not control the project you cite in your message, even though it incorrectly lists this Github project as its Homepage.

Use [rhash-Rhash](https://pypi.org/project/rhash-Rhash/) PyPi project instead.
