### ISSUE TITLE
1.4.5 Build issue

### ISSUE THREAD

**Issue by Perkolator** [rhash/RHash#269]
Trying to build the new 1.4.5 version in Linux Mint 20.3 and receiving an error:

```
$ ./configure --enable-static=librhash --enable-openssl=runtime && make

Checking for sources ... RHash 1.4.5 
Checking for target OS ... Linux 
Checking for cc version ... gcc 9.4.0 
Checking for linker support for dlopen ... yes 
Checking for linker support for --version-script ... yes 
Checking for gettext ... found 
Checking for OpenSSL ... runtime 
Writing config.mak
Writing librhash/config.mak
Writing dist/librhash.pc
Writing dist/rhash.1
cc -c -DUSE_GETTEXT -O2 -DNDEBUG -pipe -ffunction-sections -fdata-sections -fomit-frame-pointer -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations -Wdeclaration-after-statement  calc_sums.c -o calc_sums.o
In file included from calc_sums.h:5,
                 from calc_sums.c:3:
common_func.h:147:41: error: missing binary operator before token "("
  147 |     (defined(__clang__) && __has_builtin(__builtin_ctz))
      |                                         ^
make: *** [Makefile:160: calc_sums.o] Error 1
```

`build-essential` and `libssl-dev` are installed before trying to build. Building 1.4.4 version works fine.

EDIT: Additional question: what is the "--one-hash" formatting option that is mentioned in the changelog? There's no documentation of what it does.

**Comment by rhash** [comment]
Create the patch from c2caef7632b40f386790a48c010079a0fed27898 to compile by gcc-8/gcc-9.

To compile by gcc <= 7 patches from commits c2caef7632b40f386790a48c010079a0fed27898 and 1fa666a56c65230d7b4f3c66a626f06bc620124d shall be applied.

**Comment by rhash** [comment]
> EDIT: Additional question: what is the "--one-hash" formatting option that is mentioned in the changelog? There's no documentation of what it does.

Read the program manual.
