### ISSUE TITLE
[PENDING] Обработка длинного пути

### ISSUE THREAD

**Issue by sergeevabc** [rhash/RHash#28]
Запускаю
```
rhash --sha1 -o openserver.sha1 -r D:\OpenServer
```
Со временем начинают сыпаться ошибки вроде этой
```
RHash: D:\OpenServer\domains\localhost\content\someday\sandbox\vendor\symfony\src\Symfony\Bundle\DoctrineMongoDBBundle\Tests\DependencyInjection\Fixtures\Bundles\XmlBundle\Resources\config\doctrine\metadata\mongodb\Fixtures.Bundles.XmlBundle.Document.Test.xml: No such file or directory
```
На этом же месте падает консольная [Exf][1], а вот [OpenSFV][2] отрабатывает нормально.

[1]: http://www.exactfile.com/
[2]: https://sourceforge.net/projects/opensfv/

**Comment by sergeevabc** [comment]
Алексей, ку-ку. :)

**Comment by rhash** [comment]
Очевидно, это проблема с длинными, около 250 символов, путями файлов.

Надо исследовать как это можно обойти. Вероятная причина бага - в ограниченности WinAPI, представленного в MSYS (MSYS используется для сборки виндовой версии).

**Comment by data-man** [comment]
@sergeevabc

А если так?
rhash --sha1 -o openserver.sha1 -r \\?\D:\OpenServer

**Comment by sergeevabc** [comment]
@data-man, UNC-путь? Действительно, временно можно так, пока Алексей думает.
Правда, редкая программа впоследствии сможет верифицировать подобный вывод.

**Comment by rhash** [comment]
Багфикс внесён в master: 1a2c0e8336ba7c88de3575399928ee0c4dd88341

**Comment by rhash** [comment]
Fixed in v1.3.5.

**Comment by sergeevabc** [comment]
Фикс работает: Спасибо!

Хм, ```rhash.exe``` вырос с ~600 KiB до 2 MiB, это задумка или можно оптимизировать?

**Comment by rhash** [comment]
Это статически влинкованная поддержка русского и других языков (библиотека Gettext). Можно gettext поставлять в виде dll-ек, но нужно потрудиться, чтоб при их удалении продолжало запускаться.

**Comment by sergeevabc** [comment]
А зачем в консольной утилите для хэширования поддержка других языков, когда в ходу пару операций — посчитать и проверить, плюс набор ключей-алгоритмов, ну да автору виднее.
