### ISSUE TITLE
[EXPIRED] SFV без даты и прочих атрибутов

### ISSUE THREAD

**Issue by sergeevabc** [rhash/RHash#29]
Сейчас лишь ключ ```--sfv``` среди ```--simple``` и ```--bsd``` даёт классический вывод вроде
```
D:\OpenServer\Open Server x64.exe 100C69E7
``` 
Однако перед этим он городит
```
; 8753152  15:26.47 2016-06-26 D:\OpenServer\Open Server x64.exe
```
Хотелось бы иметь возможность исключить эту информацию.

**Comment by rhash** [comment]
Use:
rhash -p "%p %C\n"  FILES...

  Regards,
  Aleksey

**Comment by sergeevabc** [comment]
Работает, Алексей, спасибо.
