### ISSUE TITLE
Using -r when updating does not search sub directories.

### ISSUE THREAD

**Issue by Hashnoob** [rhash/RHash#33]
I'm wondering if I'm missing something or is this just a limitation of the update command?
If anyone has a workaround please post it.

Issue: Using -r with -u will not search sub directories.

This is working great and finds all files in all sub directories as expected.
Creating: "rhash -r * -M --sfv -o hash.md5"

When trying to update hash.md5 RHash only finds new files in the starting directory.
Updating: "rhash -r -u hash.md5 -M --sfv"

Any help would be appreciated. :)

**Comment by gavtroy** [comment]
Agree. #16 is the same complaint, and @rhash's response sounds like it's intended behavior. But it's a strange gap in the feature list, where -r and -u are both supported individually, but not together.

**Comment by rhash** [comment]
On Fri, Mar 24, 2017, Ferenc wrote:

Hi Aleksey,

I don't see why "-u" adds files of the folder of the hash file. I would rather like an update feature that takes same file list as creating new file. So e.g.

rhash -r mydir >crc.txt
then
rhash -u crc.txt -r mydir

You understand?

Also:

rhash file1 file2 file3 >crc.txt

rhash -u crc.txt file1 file2 file3

What do you think?

(Of course this would need to be a new option to avoid modifying -u. If you think above makes sense. I wanted to use your tool for storing several subdirs recursively CRC, but in a separate location.)

Thank you,
Ferenc

**Comment by rhash** [comment]
This behavior was asked to be changed several times already, so I consider introducing new option for this or even changing behavior of the existing --update option with new option for the old behavior.

**Comment by Hashnoob** [comment]
Thank you for your consideration!

**Comment by obetz** [comment]
Sadly, v1.3.8 released 2019-02 still doesn't support recursive update.

Therefore it seems to be impossible to check a file tree automatically, including new directories.

**Comment by fred777** [comment]
+1 

I also just stumbled upon this issue when I tried to update checksum file of a file tree recursively

**Comment by rhash** [comment]
I consider this feature the most important among other (big) feature requests. So I hope to find time for it to include in the nearest release.

**Comment by rhash** [comment]
The feature is implemented by 74f79c027a541b02a0ad58f8fdd7d7d0a995b19d and 10434e9e0462dcbe322ba67acd31d8d39fab17e7. The old behavior is abandoned. 

Usage:
`rhash --sha1 -r --update=hash_file.sha1 directory1/ directory2/`
or just:
`rhash -Hru hash_file.sha1 directory1/ directory2/`

**Comment by rhash** [comment]
The feature is included in v1.3.9.
