### ISSUE TITLE
osx port

### ISSUE THREAD

**Issue by xantares** [rhash/RHash#34]
hello,
currently rhash cannot be compiled on osx, is it in your roadmap ?
all I find is an old homebrew patch: https://sourceforge.net/p/rhash/feature-requests/23/
may I suggest using cmake instead of Makefiles ? I could write an initial port if your ok with the principle, (that would also allow compilation with msvc).

**Comment by rhash** [comment]
Hello. 
I've read your discussion.
First, thanks for the librhash-osx.patch. The dylib libraries suuport can be merged with small changes.

Second, about cmake. Makefiles were chosen to improve portability and minimize dependency on the build system. And I want to keep that feature. Maintaining two build systems would be a hassle. So, at least for now, let other projects, incorporating librhash, maintain its cmake scripts.

**Comment by rhash** [comment]
While RHash should be built by raw makefiles by default, it's acceptable to auto-generate cmakefiles by a shell script and to distribute them in a separate directory like '/build/cmake/'.

Also note that dylib support was partly merged into librhash. Run `make -C librhash dylib` to build the library.

**Comment by rhash** [comment]
Current development version (master branch) allows to compile RHash for OSX using commands:

`make -C librhash dylib test-dylib`
`make build-shared test-shared SHAREDLIB=librhash/librhash.0.dylib`

**Comment by jakirkham** [comment]
Why does the shared library need to be specified by the user?

**Comment by rhash** [comment]
I think osx binary should not be compiled by user.
User shall use some binary package, built by some script.
The two commands above are easy enough to add to such script.

**Comment by jakirkham** [comment]
My concern is it seems like whoever builds the package is being asked to version the library, which doesn't seem like something they should be doing. Is it possible for rhash's build scripts to take care of the library version?

**Comment by rhash** [comment]
You are right. Fixed by commit cdaf43862229fb0f10d2b6b7448bcded2ef8edde ;)

**Comment by rhash** [comment]
The fix is included into RHash v1.3.6.

**Comment by jakirkham** [comment]
Thank you. :)

So how should we be building RHash now?

**Comment by rhash** [comment]
I think RHash on osx should be compiled as:
~~~
configure --sysconfdir=/etc --prefix=/usr --enable-gettext
--enable-openssl-runtime --extra-cflags=-I/usr/local/opt/openssl/include"
make && make test
make instlall
~~~

**Comment by rhash** [comment]
I think RHash on osx should be compiled as:
~~~
configure --sysconfdir=/etc --prefix=/usr --enable-gettext
--enable-openssl-runtime --extra-cflags=-I/usr/local/opt/openssl/include"
make && make test
make instlall
~~~
