### ISSUE TITLE
PHP binding build error with PHP 7.0

### ISSUE THREAD

**Issue by guoxiaoqiao** [rhash/RHash#37]
Here is my build log.

[root@localhost php]# phpize 
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
[root@localhost php]# ls 
acinclude.m4    build         config.m4   configure.in  Makefile.global  php_rhash.c    tests
aclocal.m4      config.guess  config.sub  install-sh    missing          php_rhash.h
autom4te.cache  config.h.in   configure   ltmain.sh     mkinstalldirs    run-tests.php
[root@localhost php]# ./configure 
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for RHash support... yes, shared
checking for RHash in default path... found in /usr
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
[root@localhost php]# ls -al
总用量 1772
drwxr-xr-x 7 root root   4096 7月  20 19:26 .
drwxr-xr-x 8 root root   4096 7月  20 19:25 ..
-rw-r--r-- 1 root root  82479 7月  20 19:26 acinclude.m4
-rw-r--r-- 1 root root 392504 7月  20 19:26 aclocal.m4
drwxr-xr-x 2 root root   4096 7月  20 19:26 autom4te.cache
drwxr-xr-x 2 root root   4096 7月  20 19:26 build
-rwxr-xr-x 1 root root  42938 7月  20 19:26 config.guess
-rw-r--r-- 1 root root   1888 7月  20 19:26 config.h
-rw-r--r-- 1 root root   1750 7月  20 19:26 config.h.in
-rw-r--r-- 1 root root  20670 7月  20 19:26 config.log
-rw-r--r-- 1 root root   1086 7月  20 19:25 config.m4
-rwxr-xr-x 1 root root     58 7月  20 19:26 config.nice
-rwxr-xr-x 1 root root  49208 7月  20 19:26 config.status
-rwxr-xr-x 1 root root  35987 7月  20 19:26 config.sub
-rwxr-xr-x 1 root root 402466 7月  20 19:26 configure
-rw-r--r-- 1 root root   4698 7月  20 19:26 configure.in
-rw-r--r-- 1 root root      0 7月  20 19:26 .deps
drwxr-xr-x 2 root root   4096 7月  20 19:26 include
-rw-r--r-- 1 root root      0 7月  20 19:26 install-sh
-rwxr-xr-x 1 root root 293052 7月  20 19:26 libtool
-rw-r--r-- 1 root root 283474 7月  20 19:26 ltmain.sh
-rw-r--r-- 1 root root   9147 7月  20 19:26 Makefile
-rw-r--r-- 1 root root      0 7月  20 19:26 Makefile.fragments
-rw-r--r-- 1 root root   7236 7月  20 19:26 Makefile.global
-rw-r--r-- 1 root root    607 7月  20 19:26 Makefile.objects
-rw-r--r-- 1 root root      0 7月  20 19:26 missing
-rw-r--r-- 1 root root      0 7月  20 19:26 mkinstalldirs
drwxr-xr-x 2 root root   4096 7月  20 19:26 modules
-rw-r--r-- 1 root root  18216 7月  20 19:25 php_rhash.c
-rw-r--r-- 1 root root    815 7月  20 19:25 php_rhash.h
-rw-r--r-- 1 root root  82956 7月  20 19:26 run-tests.php
drwxr-xr-x 2 root root   4096 7月  20 19:25 tests
[root@localhost php]# make
/bin/sh /root/RHash/bindings/php/libtool --mode=compile cc  -I. -I/root/RHash/bindings/php -DPHP_ATOM_INC -I/root/RHash/bindings/php/include -I/root/RHash/bindings/php/main -I/root/RHash/bindings/php -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/RHash/bindings/php/php_rhash.c -o php_rhash.lo 
libtool: compile:  cc -I. -I/root/RHash/bindings/php -DPHP_ATOM_INC -I/root/RHash/bindings/php/include -I/root/RHash/bindings/php/main -I/root/RHash/bindings/php -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/RHash/bindings/php/php_rhash.c  -fPIC -DPIC -o .libs/php_rhash.o
```
/root/RHash/bindings/php/php_rhash.c:145:1: error: unknown type name 'zend_object_value'
 static zend_object_value rhash_create_handler(zend_class_entry *type TSRMLS_DC);
 ^
/root/RHash/bindings/php/php_rhash.c: In function 'zm_startup_rhash':
/root/RHash/bindings/php/php_rhash.c:184:26: warning: assignment from incompatible pointer type [enabled by default]
  rhash_ce->create_object = rhash_create_handler;
                          ^
/root/RHash/bindings/php/php_rhash.c: In function 'zif_rhash_get_name':
/root/RHash/bindings/php/php_rhash.c:278:52: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
  RETURN_STRING(rhash_get_name((unsigned)hash_id), 1);
                                                    ^
/root/RHash/bindings/php/php_rhash.c:278:2: error: 'RETURN_STRING' undeclared (first use in this function)
  RETURN_STRING(rhash_get_name((unsigned)hash_id), 1);
  ^
/root/RHash/bindings/php/php_rhash.c:278:2: note: each undeclared identifier is reported only once for each function it appears in
/root/RHash/bindings/php/php_rhash.c: In function 'zif_rhash_msg':
/root/RHash/bindings/php/php_rhash.c:305:34: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
  RETURN_STRINGL(buffer, length, 1);
                                  ^
/root/RHash/bindings/php/php_rhash.c:305:2: error: 'RETURN_STRINGL' undeclared (first use in this function)
  RETURN_STRINGL(buffer, length, 1);
  ^
/root/RHash/bindings/php/php_rhash.c: In function '_php_rhash_stream':
/root/RHash/bindings/php/php_rhash.c:313:23: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   rhash_object *obj = (rhash_object *)zend_object_store_get_object(getThis() TSRMLS_CC);
                       ^
/root/RHash/bindings/php/php_rhash.c: In function 'zif_rhash_file':
/root/RHash/bindings/php/php_rhash.c:378:41: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
  RETURN_STRINGL(buffer, buffer_length, 1);
                                         ^
/root/RHash/bindings/php/php_rhash.c:378:2: error: 'RETURN_STRINGL' undeclared (first use in this function)
  RETURN_STRINGL(buffer, buffer_length, 1);
  ^
/root/RHash/bindings/php/php_rhash.c: In function 'zif_rhash_magnet':
/root/RHash/bindings/php/php_rhash.c:412:43: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
  RETURN_STRINGL(buffer, buffer_size - 1, 0);
                                           ^
/root/RHash/bindings/php/php_rhash.c:412:2: error: 'RETURN_STRINGL' undeclared (first use in this function)
  RETURN_STRINGL(buffer, buffer_size - 1, 0);
  ^
/root/RHash/bindings/php/php_rhash.c: At top level:
/root/RHash/bindings/php/php_rhash.c:428:1: error: unknown type name 'zend_object_value'
 static zend_object_value rhash_create_handler(zend_class_entry *class_type TSRMLS_DC)
 ^
/root/RHash/bindings/php/php_rhash.c: In function 'rhash_create_handler':
/root/RHash/bindings/php/php_rhash.c:431:2: error: unknown type name 'zend_object_value'
  zend_object_value retval;
  ^
/root/RHash/bindings/php/php_rhash.c:446:8: error: request for member 'handle' in something not a structure or union
  retval.handle = zend_objects_store_put(obj, NULL,
        ^
/root/RHash/bindings/php/php_rhash.c:447:3: warning: passing argument 1 of 'zend_objects_store_put' from incompatible pointer type [enabled by default]
   rhash_free_storage, NULL TSRMLS_CC);
   ^
In file included from /usr/include/php/Zend/zend_globals.h:35:0,
                 from /usr/include/php/Zend/zend_compile.h:657,
                 from /usr/include/php/Zend/zend_modules.h:26,
                 from /usr/include/php/Zend/zend_API.h:27,
                 from /usr/include/php/main/php.h:39,
                 from /root/RHash/bindings/php/php_rhash.c:7:
/usr/include/php/Zend/zend_objects_API.h:58:15: note: expected 'struct zend_object *' but argument is of type 'struct rhash_object *'
 ZEND_API void zend_objects_store_put(zend_object *object);
               ^
/root/RHash/bindings/php/php_rhash.c:447:3: error: too many arguments to function 'zend_objects_store_put'
   rhash_free_storage, NULL TSRMLS_CC);
   ^
In file included from /usr/include/php/Zend/zend_globals.h:35:0,
                 from /usr/include/php/Zend/zend_compile.h:657,
                 from /usr/include/php/Zend/zend_modules.h:26,
                 from /usr/include/php/Zend/zend_API.h:27,
                 from /usr/include/php/main/php.h:39,
                 from /root/RHash/bindings/php/php_rhash.c:7:
/usr/include/php/Zend/zend_objects_API.h:58:15: note: declared here
 ZEND_API void zend_objects_store_put(zend_object *object);
               ^
/root/RHash/bindings/php/php_rhash.c:448:8: error: request for member 'handlers' in something not a structure or union
  retval.handlers = &rhash_object_handlers;
        ^
/root/RHash/bindings/php/php_rhash.c: In function 'zim_RHash___construct':
/root/RHash/bindings/php/php_rhash.c:471:8: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  obj = (rhash_object *)zend_object_store_get_object(getThis() TSRMLS_CC);
        ^
/root/RHash/bindings/php/php_rhash.c: In function 'zim_RHash_update':
/root/RHash/bindings/php/php_rhash.c:483:22: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  rhash_object *obj = (rhash_object *)zend_object_store_get_object(object TSRMLS_CC);
                      ^
/root/RHash/bindings/php/php_rhash.c: In function 'zim_RHash_update_stream':
/root/RHash/bindings/php/php_rhash.c:506:2: warning: passing argument 1 of 'zend_fetch_resource2_ex' from incompatible pointer type [enabled by default]
  php_stream_from_zval_no_verify(stream, &handle);
  ^
In file included from /usr/include/php/Zend/zend_API.h:28:0,
                 from /usr/include/php/main/php.h:39,
                 from /root/RHash/bindings/php/php_rhash.c:7:
/usr/include/php/Zend/zend_list.h:66:16: note: expected 'struct zval *' but argument is of type 'struct zval **'
 ZEND_API void *zend_fetch_resource2_ex(zval *res, const char *resource_type_name, int resource_type, int resource_type2);
                ^
/root/RHash/bindings/php/php_rhash.c: In function 'zim_RHash_final':
/root/RHash/bindings/php/php_rhash.c:533:22: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  rhash_object *obj = (rhash_object *)zend_object_store_get_object(object TSRMLS_CC);
                      ^
/root/RHash/bindings/php/php_rhash.c: In function 'zim_RHash_reset':
/root/RHash/bindings/php/php_rhash.c:546:22: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  rhash_object *obj = (rhash_object *)zend_object_store_get_object(object TSRMLS_CC);
                      ^
/root/RHash/bindings/php/php_rhash.c: In function 'zim_RHash_hashed_length':
/root/RHash/bindings/php/php_rhash.c:558:22: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  rhash_object *obj = (rhash_object *)zend_object_store_get_object(getThis() TSRMLS_CC);
                      ^
/root/RHash/bindings/php/php_rhash.c: In function '_php_get_hash':
/root/RHash/bindings/php/php_rhash.c:571:22: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  rhash_object *obj = (rhash_object *)zend_object_store_get_object(getThis() TSRMLS_CC);
                      ^
/root/RHash/bindings/php/php_rhash.c:577:34: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
  RETURN_STRINGL(buffer, length, 1)
                                  ^
/root/RHash/bindings/php/php_rhash.c:577:2: error: 'RETURN_STRINGL' undeclared (first use in this function)
  RETURN_STRINGL(buffer, length, 1)
  ^
/root/RHash/bindings/php/php_rhash.c:578:1: error: expected ';' before '}' token
 }
 ^
/root/RHash/bindings/php/php_rhash.c: In function 'zim_RHash_magnet':
/root/RHash/bindings/php/php_rhash.c:629:22: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  rhash_object *obj = (rhash_object *)zend_object_store_get_object(getThis() TSRMLS_CC);
                      ^
/root/RHash/bindings/php/php_rhash.c:641:40: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
  RETURN_STRINGL(buffer, buf_size - 1, 0);
                                        ^
/root/RHash/bindings/php/php_rhash.c:641:2: error: 'RETURN_STRINGL' undeclared (first use in this function)
  RETURN_STRINGL(buffer, buf_size - 1, 0);
  ^
make: *** [php_rhash.lo] 错误 1
```
[root@localhost php]#

**Comment by rhash** [comment]
Thanks for reporting it.

It seems that Zend API have changed and the module needs to be ported to PHP7.

**Comment by rhash** [comment]
PHP7 supported, commit: 18582f8cb55eb7b809bfc7ea9fbe0a1bcaec19c0

**Comment by guoxiaoqiao** [comment]
Thank you, I will try to it later.

**Comment by rhash** [comment]
Done in v1.3.5.
