### ISSUE TITLE
Does an up to date release tarball exist newer than 1.3.2 ? 

### ISSUE THREAD

**Issue by posix2001** [rhash/RHash#38]
I see a large collection of new files in the git repo that do not exist in the 1.3.2 tarball.  Seems as if many problems have been fixed already such as the rhash_ctz() function which won't even compile because var v is not defined anywhere inside byte_order.c as well as a ton of other changes.  Not sure how to proceed with the existing gitrepo as there are now directories for java and mono pieces that did not exist at all in the 1.3.2 release. Regardless, seems librhash.so.1 is needed to build cmake which is needed to buid MySQL so the RHash code is in front of me at the moment.  I see at https://sourceforge.net/projects/rhash/files/rhash/1.3.4/  that the 1.3.2 release is said to be the "latest" but clearly there must be a 1.3.4 or even newer?

**Comment by rhash** [comment]
SourceForge couldn't detect your OS, so it looked for the latest package of type 'Other', and it incorrectly pointed to v1.3.2. I suppose I've repaired it.

Could you, please, verify that SF shows now the latest package as v1.3.4?

**Comment by blastwave** [comment]
Yes Sir!  Awesome.  SourceForge now says "Looking for the latest version? Download rhash-1.3.4-src.tar.gz (249.4 kB) " which is perfect. I am running Debian 9 Linux as the desktop here to see that however the file needs to get to a Solaris server to be compiled with the Oracle Studio 12.5 dev tools which are really, offensively, incredibly, strict C99 compliance on a POSIX box.  So I will let you know how that goes. If there are any GNU extensions in there then we will bork up badly and quickly. I'll stay in touch.

**Comment by blastwave** [comment]
oh oh .. the download fails. What is the SHA256 hash?  Can we get a mirror going at some big university?  The FTP site for University of Waterloo Computer Science Dept is amazing. Maybe there? see http://mirror.csclub.uwaterloo.ca/mysql/Downloads/MySQL-5.7 for example.

**Comment by rhash** [comment]
mirror.csclub.uwaterloo.ca has usual debian and ubuntu mirrors:
http://mirror.csclub.uwaterloo.ca/debian/pool/main/r/rhash/rhash_1.3.4.orig.tar.gz
http://mirror.csclub.uwaterloo.ca/ubuntu/pool/main/r/rhash/rhash_1.3.4.orig.tar.gz

**Comment by blastwave** [comment]
Hey, I never even knew that existed there. The real question is if the files names "orig" really perfectly match the rhash-1.3.4.tar.gz SHA256 sigs. I will have to check.

**Comment by rhash** [comment]
According to https://github.com/rhash/RHash/blob/master/README official RHash releases are located at http://sf.net/projects/rhash/files/rhash/ ,
the Download section of official rhash website points to the same location.

From another side, Github has took initiative to call tarballs generated from git tags as 'Releases': https://github.com/rhash/RHash/releases , but they have different hash sums.

This situation encouraged uploader of the last Debian RHash package to take sourceball from 'Git Releases'. Consequently hash sums of current Debian/Ubuntu tarball differ from SF tarball.

I'm thinking on making future version from Git tarballs to eliminate this confusion.

**Comment by blastwave** [comment]
Thank you for the reply. You may see my concern here as I am building into a very strict environment and I must "check in" a source release tarball with a SHA256 hash that matches a release document somewhere. Then at that point patches may be applied however they too must be documented or at least logged as official patches. The end result is a very stable and reliable system wherein every file and every piece has a tracked history as well as a manifest.  Security and stability are the words for the day and well, you have heard it all before. So I will go after the "official" 1.3.4 tarball and then hopefully there is a README file somewhere with a hash report and then I can move onwards.

**Comment by blastwave** [comment]
Could the README at https://github.com/rhash/RHash/blob/master/README be updated to include a section that says "Official Releases" with a link to where those tarballs are ( gzipped or bzip2ed or xz etc ) with SHA256 hash sums?  Without the SHA256 hash then a tarball can be from anywhere and look "official". That would make the idea of an actual line in the sand release very real.  The README does say "The latest source code can be obtained from Git repository by command: git clone git://github.com/rhash/RHash.git" however this is a moving picture as opposed to an actual version release. Also, and this is what I am working on, the requirements seems to say GCC or the Intel compiler. However I am trying with a very strict C99 compiler on Solaris 10 and this should be possible. As I run into things ( which I have ) I will share. Certainly the link stage has been interesting.

**Comment by rhash** [comment]
[README](https://github.com/rhash/RHash/blob/master/README) already has such line:

![image](https://user-images.githubusercontent.com/844517/29042953-d1f30b9a-7bc1-11e7-83fb-99412d6c7a2f.png)

SourceForge provides only SHA1 and MD5 hash sums for each release tarball (press the (i) icon to the right of a file). You can ask them to generate also SHA-256 or even SHA3.

I would prefer to upload strong pgp signatures instead of hash files, since hash files can be generated by anybody.

For your convinience, hash sums for the official v1.3.4 tarball are:
MD5   (rhash-1.3.4-src.tar.gz) = 0b51010604659e9e99f6307b053ba13b
SHA1  (rhash-1.3.4-src.tar.gz) = 411d8c7ba84fa9763bc49fa2fd3a7587712fd52c
SHA-256 (rhash-1.3.4-src.tar.gz) = 406662c4703bd4cb1caae26f32700951a5e12adf39f141d3f40e0b461b1e9e49
SHA3-256 (rhash-1.3.4-src.tar.gz) = af5ffcabc427ffdfb6d523f07a0bd997fff6ea148f27e28540ddc0a05c1a7a53

**Comment by blastwave** [comment]
Thank you, I will let you know what happens when I try to compile all this with a strict C99 compiler.

**Comment by posix2001** [comment]
A year later or so and I see RHash has moved "officially" to github : 

Project Home Page: http://rhash.sourceforge.net/
Official Releases: https://github.com/rhash/RHash/releases/

So that takes care of the confusion.
