### ISSUE TITLE
Request for Sort Options

### ISSUE THREAD

**Issue by newhoa** [rhash/RHash#39]
This is a really great program, thank you so much!

I was wondering if there were sorting options, I don't seem to see any but maybe I've missed it. rhash sorts alphabetically ignoring case, which is much better than most hash software already (thank you).

It would be nice to have the ability to sort subdirectories first or last (--dirsfirst or --dirslast) when using the --recursive option.

Sorting by name(case sensitive or not),size,mtime,ctime,etc would be nice too, but sorting directories first or last would be really helpful with productivity.

Sorry if this option is present and I've overlooked it. And if it's something you're not interested in I can understand that. Thank you again so much for this software, I really love it!

**Comment by rhash** [comment]
This is not an rhash task. I believe rhash instead should support accepting filelists [1] (files containing file paths to process), which should be generated by some other utililty.

[1] https://sourceforge.net/p/rhash/feature-requests/3/

**Comment by Perkolator** [comment]
Although this is closed, I still leave my vote for doing something about the "recursive" sorting. Here's a simple example why IMO:

Test files/folders:
```
$ ls -R
.:
folder  text1  text2  text3  text4  text5

./folder:
file00  file01  file02  file03  file04  file05  file06  file07  file08  file09  file10
```
```
$ rhash --crc32 --recursive *
; Generated by RHash v1.3.9 on 2021-02-21 at 08:05.33
; Written by Kravchenko Aleksey (Akademgorodok) - http://rhash.sf.net/
;
;            0  08:04.10 2021-02-21 folder/file06
;            0  08:04.10 2021-02-21 folder/file09
;            0  08:04.10 2021-02-21 folder/file10
;            0  08:04.10 2021-02-21 folder/file05
;            0  08:04.10 2021-02-21 folder/file08
;            0  08:04.10 2021-02-21 folder/file03
;            0  08:04.10 2021-02-21 folder/file04
;            0  08:04.10 2021-02-21 folder/file02
;            0  08:04.10 2021-02-21 folder/file01
;            0  08:04.10 2021-02-21 folder/file07
;            0  08:04.10 2021-02-21 folder/file00
;            0  08:01.41 2021-02-21 text1
;            0  08:01.48 2021-02-21 text2
;            0  08:01.53 2021-02-21 text3
;            0  08:01.58 2021-02-21 text4
;            0  08:02.02 2021-02-21 text5
folder/file06 00000000
folder/file09 00000000
folder/file10 00000000
folder/file05 00000000
folder/file08 00000000
folder/file03 00000000
folder/file04 00000000
folder/file02 00000000
folder/file01 00000000
folder/file07 00000000
folder/file00 00000000
text1 00000000
text2 00000000
text3 00000000
text4 00000000
text5 00000000
```
While files in current folder are always sorted nicely, all files in subfolders are seemingly in random order. Sometimes, YMMV, it's good to have the files properly sorted in hash files (e.g. one has to manually fiddle with the hash file).

I don't see any items in newer versions changelogs that would affect recursive sorting.

**Comment by rhash** [comment]
The sorting feature is not that simple to implement.

1. File names are generally represented as UTF strings, which require comparison of strings using a _collation ordering_, because different byte sequences can correspond to the same UTF symbol. Such feature would require separate implementation on Windows, which is bad at supporting standard C locales.
2. For directories with very big number of files, the sorting step can reduce performance.

Currently one can create a sorted file-list by other utilities and then pass it to RHash using the `--filelist <FILELIST>` option. Because of this workaround, the sorting feature has a low priority.
