### ISSUE TITLE
Точка входа в процедуру _vsnprintf_s не найдена в библиотеке DLL msvcrt.dll

### ISSUE THREAD

**Issue by Skif-off** [rhash/RHash#40]
Версия 1.3.5 на WinXP (с 1.3.4 и ниже вроде порядок).
В файле https://sourceforge.net/projects/rhash/files/rhash/1.3.5/README.txt указаны системные требования:

> The Win32 version requires: Win `XP`/`2K`/Vista/7/8/10

Функция `_vsnprintf_s` присутствует только в WinVista+, похоже, дело в версии MinGW/MSYS. Возможно ли исправить?

P.S. Спасибо за продолжение разработки, пользовался 1.3.3, случайно узнал.

**Comment by rhash** [comment]
Спасибо, за присланный баг.

Версия 1.3.5 начала использовать vsnprintf_s, подумаю как это обойти.

**Comment by rhash** [comment]
Ориентировочный план - выпустить патч, не обещаю только, что быстро)

**Comment by Skif-off** [comment]
Спасибо, подождём.

**Comment by rhash** [comment]
Исправлено: [Download RHash 1.3.5](https://sourceforge.net/projects/rhash/files/rhash/1.3.5/).

**Comment by Skif-off** [comment]
Спасибо, работает.
