### ISSUE TITLE
Падение скорости работы

### ISSUE THREAD

**Issue by Skif-off** [rhash/RHash#41]
Заинтересовавшись подросшим размером бинарников, списал часть на локализацию, но попутно наткнулся на старый скрипт тестирования скорости и в голову внезапно пришла мысль проверить: результат несколько опечалил.
```
x86      1.3.3 | 1.3.4 | 1.3.5
------------------------------
crc32  |  3502 |  3277 |  8069
md5    |  3544 |  3563 |  7076
sha1   |  7418 |  8869 |  8786
sha256 | 10858 | 10758 | 12021
sha512 | 27153 | 26154 | 29244
------------------------------
x64      1.3.3 | 1.3.4 | 1.3.5
------------------------------
crc32  |  3415 |  3372 |  7974
md5    |  4140 |  3762 |  7277
sha1   |  7655 |  7734 | 10618
sha256 |  9181 |  9827 | 11051
sha512 |  5812 |  6723 | 13606
```
Время в миллисекундах, среднее арифметическое по трём замерам, округлял по первому знаку после запятой.

Возможно ли что-нибудь сделать?

P.S. Результат ```sha512``` под х64 особенно неожиданный, в том числе в сравнении с ```sha256```.

**Comment by rhash** [comment]
Речь, очевидно, о Windows версии.

1. Попробуйте провести бенчмарк алгоритмов (без i/o) следующими командами:
rhash --benchmark --openssl="" --crc32
rhash --benchmark --openssl="" --md5
...
rhash --benchmark --openssl="" --sha512

2. На каком CPU и каком Windows проводился бенчмар?

Под подозрением пока что обновившийся компилятор и система ввода-вывода, т.к. алгоритмы почти не затрагивались.

**Comment by Skif-off** [comment]
1. Не понял, как в простом виде представить, поэтому [залил чуть отформатированный лог](https://yadi.sk/i/vq-sIRUa3MK5bX). Тут получается разница не такая заметная, хотя опять `sha256`/`sha512` несколько выбивается?

2. AMD Phenom II X4 965 (C3), Win7x64 (PE, но по идее это не должно быть проблемой).

P.S. Первый раз проверял что-то типа "в боевых условиях", только вывод в консоль, чтобы не тратить ресурсы на запись в файлы:
```autoit
rhash.exe -r --crc32 --sfv "path\*.*"
rhash.exe -r --md5 --printf="%m *%p\r\n" "path\*.*"
rhash.exe -r --sha1 --printf="%h *%p\r\n" "path\*.*"
rhash.exe -r --sha256 --printf="%{sha-256} *%p\r\n" "path\*.*"
rhash.exe -r --sha512 --printf="%{sha-512} *%p\r\n" "path\*.*"
```
Использовал AutoIt, функции `TimerInit()`, `RunWait()` и `TimerDiff()`.

**Comment by rhash** [comment]
В логе бенчмарка наиболее точный показатель - CPB (CPU Cycles Per Byte), т.к. результаты алгоритма измеряющего в MBps немного рандомизируются кэшем процессора и тактами (недостаточно точного для нас) on-board таймера.

По CPB видно, что для **win32**:
скорость crc32 и md5 не менялась,
было проседание sha1,sha256,sha512 в 1.3.4, которое самовылечилось.

Для **win64**:
crc32 не менялся, md5 - мелкое ускорение в 1.3.5 (вероятно, в пределах погрешностей),
sha1 - проседание в 1.3.4, исчезнувшее в 1.3.5,
sha256 и sha512 - замедлились на 12.4% и 14.8%, что требует изучения коммитов, затрагивавших алгоритмы.

Все остальные изменения в изначальном тесте связаны с I/O, и, вероятно, вызваны изменениями в glibc. См. также [#50 Speed issue](https://sourceforge.net/p/rhash/bugs/50/).

С sha256 и sha512 нужно изучать причины, но иногда ускорение на Intel CPU ведёт к проседанию на AMD. С этим уже может помочь только индивидуальная сборка с опциями под конкретный процессор ;)

**Comment by Skif-off** [comment]
> sha256 и sha512 - замедлились на 12.4% и 14.8%, что требует изучения коммитов, затрагивавших алгоритмы.

Главное, что вы в курсе, тут я вам, к сожалению, не помощник :)

> иногда ускорение на Intel CPU ведёт к проседанию на AMD.

Это да, слышал, хотя во всём этом, мягко говоря, не силён, в `Makefile` вижу `-march=i586 -mcpu=pentiumpro` - это же вроде не такая сильная оптимизация под конкретную платформу?

RHash использует SIMD-инструкции? Как, например, FFmpeg (где-то читал), который написан с ассемблерными вставками так, что независимо от флагов компиляции будет использовать доступные наборы инструкций. Т.е. если вдруг поставлю `-march=amdfam10` (_CPUs based on AMD Family 10h cores with x86-64 instruction set support. (This supersets MMX, SSE, SSE2, SSE3, SSE4A, 3DNow!, enhanced 3DNow!, ABM and 64-bit instruction set extensions.)_) получу ли реальное ускорение от всего этого добра? Где-то слышал, что просто включение в компиляторе ~~ничего~~ мало что даёт, зато запросто ограничивает список совместимого железа.

P.S. Запустил бенчмарк с `--sha512` на Xubuntu x64 - выдало CPB=9,37: покопался в исходниках, похоже, почему-то выпилили `-march=i586 -mcpu=pentiumpro`, либо значения берутся из какого-то конфига вне папки исходников. При этом в документации Debian пишут
> However, Debian GNU/Linux stretch will not run on 586 (Pentium) or earlier processors.

Athlon XP/Intel Pentium 4 и выше, наверное `-march=i686` и судя по [подобному](https://www.linux.org.ru/forum/linux-install/13212933) даже не `-mcpu=pentium4`.
Странно.

**Comment by rhash** [comment]
Нельзя задать -march=i586 для x64 (иначе ошибка сборки: CPU you selected does not support x86-64 instruction set).

Протестировал для x64 на Ubuntu, Intel Core i7.

При сборке v1.3.3, v1.3.4, v1.3.5 с одним компилятором и одинаковыми опциями компиляции производительность SHA-256/512 не меняется. 

Так что под подозрением версия компилятора и опции сборки ;).

**Comment by Skif-off** [comment]
Имел ввиду, что для х32-систем нет никаких особых требований :)

Проверил CPB на Xubuntu x64:
```
        | оф. реп. |  скомпилил
        |  1.3.3-1 | 1.3.3 | 1.3.5
-----------------------------  
crc32   |     5,07 |  5,07 |  5,07
md5     |     4,88 |  5,73 |  5,71
sha1    |     6,36 | 13,91 | 13,89
sha-256 |    14,68 | 20,88 | 20,88
sha-512 |     9,34 | 13,41 | 13,47
(RHash: compiled without openssl support)
```
Почему такая разница? Дело только в версии компилятора и опциях сборки?

**Comment by rhash** [comment]
А есть другие предположения? :)

**Comment by sergeevabc** [comment]
Почему для замера скорости семья SHA3 использует блок 64 MiB, а не 512?
