### ISSUE TITLE
Manual should mention that check (-c) can be combined with hash option (--md5) for faster speed

### ISSUE THREAD

**Issue by hjohn** [rhash/RHash#45]
I discovered that verifying hashes with `-c` is much slower than generating them.  

I was using this command:

    rhash -c --skip-ok download.sfv

`iotop` reported disk read speeds of 30 MB/sec and `rhash` was consuming 100% CPU.

Then I thought, how does rhash know that the SFV file contains MD5 hashes?  It probably doesn't, and it runs all checksum algorithms when doing a check and sees if any of those match the value in the SFV file... that's not very efficient.

Changing the command line to:

    rhash -c --md5 --skip-ok download.sfv

...was *much* faster (just as fast as generating them), reaching speeds of 95 MB/sec with only 30% CPU use.

I think the man file should mention this ;-)

**Comment by rhash** [comment]
You are right, it should be mentioned :)

**Comment by Gooberslot** [comment]
Why can't it just look at the file extension? If a file has an extension like sha256 then it's pretty safe to assume it's not going to have md5 hashes, and if it does the person that generated the file is an idiot.

**Comment by rhash** [comment]
Hash algorithm detection by file extension is implemented by 53d3366b9e5e644fda9310829907757e63b397f6.

Also manual is updated by b0f06177e58cfbd06b2855daee38f9822f5752e1:

> If the hash algorithm is not specified by command line options
then RHash tries to detect algorithm from the extension of the hash file.
If detection fails, then all hash function of the same hash length are calculated,
and that significally slows down files verification. To speed up verification,
in such case, explicitly specify the hash algorithm in the command line.
