### ISSUE TITLE
Build error with mingw32/msys using gcc 6.3.0

### ISSUE THREAD

**Issue by satori80** [rhash/RHash#46]
Error:

win_utils.c:506:39: error: '_TRUNCATE' undeclared (first use in this function) 
   Int res = vsnprintf_s(buffer, 8192, _TRUNCATE, format, args);

I had to solve another definition issue also, but I can't even start to guess what  _TRUNCATE should define as.

**Comment by rhash** [comment]
The problem is already solved in the master branch by commit a3e64cb4f6a1dd57eab19848599883dfe0c4cd9a
