### ISSUE TITLE
rhashrc

### ISSUE THREAD

**Issue by satori80** [rhash/RHash#47]
Rhash does not seem to be honoring the 'percents=on'  in the config file. The others all seem to be working fine.

Also, --percents on the command-line works as expected.

**Comment by rhash** [comment]
The bug is now fixed in the master branch: 82ea3c6fc2f4e52d8a5a06b9c62e7ed55aa3ddb0.

Thanks for reporting it!

**Comment by satori80** [comment]
Working perfectly, thank you!

Closing issues.
