### ISSUE TITLE
[Request] Use a faster lib for crc32

### ISSUE THREAD

**Issue by noraj** [rhash/RHash#49]
I used [SFV-Check](https://github.com/Bilge/SFV-Check/blob/master/ruby/sfv_check.rb) to check a sfv file using crc32 and it was **2.56 times (256%) faster** than RHash (sfv-hash).

Running rhash benchmark show that md4 and even md5 are faster to compute than crc32.

I see that  RHash CRC32 follows the [CRC32-IEEE 802.3](http://www.xilinx.com/support/documentation/application_notes/xapp209.pdf).

But SFV-Check is using [Zlib crc32](http://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/zlib-crc32-1.html) that follows [ITU-T V.42](http://www.itu.int/rec/T-REC-V.42/e).

CRC32 is the simplest algorithm (supported by RHash) to compute so it should be the fastest.

But there are even faster algorithms, for example Intel's slicing-by-8 CRC32 is about 4 times faster than Zlib's crc32.

The [Fast CRC32](http://create.stephan-brumme.com/crc32/) article show throughput, CPU cycles/byte, time, implementations in C and a lot more stuff about all major crc32 implementation algorithms.

Can you please take a look at those faster crc32 algorithms and may be RHash will be as fast as the light one day 😄

**Comment by benbro** [comment]
Please support crc32c
https://cloud.google.com/storage/docs/hashes-etags#_CRC32C
https://github.com/google/crc32c

**Comment by noraj** [comment]
@rhash so, have you found a way to improve crc32 speed?

**Comment by data-man** [comment]
https://github.com/intel/soft-crc

> Legal Disclaimer
> ================
>THIS SOFTWARE IS PROVIDED BY INTEL"AS IS". **NO LICENSE**, EXPRESS OR
IMPLIED, BY ESTOPPEL OR OTHERWISE, TO ANY INTELLECTUAL PROPERTY RIGHTS
ARE GRANTED THROUGH USE. EXCEPT AS PROVIDED IN INTEL'S TERMS AND
CONDITIONS OF SALE, INTEL ASSUMES NO LIABILITY WHATSOEVER AND INTEL
DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTY, RELATING TO SALE AND/OR
USE OF INTEL PRODUCTS INCLUDING LIABILITY OR WARRANTIES RELATING TO
FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, OR INFRINGEMENT
OF ANY PATENT, COPYRIGHT OR OTHER INTELLECTUAL PROPERTY RIGHT.

**Comment by noraj** [comment]
@data-man So if it is unlicensed it is free for use for everyone ? else there is still a lot of other implementations http://create.stephan-brumme.com/crc32/

**Comment by rhash** [comment]
@data-man soft-crc is [licensed](https://github.com/intel/soft-crc/blob/master/LICENSE) under BSD 3-Clause License, that is more strict, than our license.

@noraj I've viewed a bit algorithms, you proposed, but, unfortunately, had no time to incorporate them. Why you need so much a faster crc? Isn't the current throughput enough?

**Comment by noraj** [comment]
@rhash It's actually slower to check the crc or my archives than trying to uncompressed them to see if it was corrupted...

**Comment by rhash** [comment]
CRC32 is speed up by commit 0b6a50af31cf953f78c8303de0f0a485a35d83e8.

**Comment by noraj** [comment]
Benchmark says that md5 is still faster than crc32 ...

```
$ rhash --crc32 -B                                                                                                                                                                      
RHash v1.3.6 benchmarking...                                                                                                                                                                                       
CRC32 512 MiB calculated in 1,025 sec, 499,410 MBps                                                                                                                                                                
CRC32 512 MiB calculated in 1,021 sec, 501,415 MBps                                                                                                                                                                
CRC32 512 MiB calculated in 1,014 sec, 504,826 MBps                                                                                                                                                                
CRC32 512 MiB calculated in 1,017 sec, 503,371 MBps                                                                                                                                                                
CRC32 2048 MiB total in 4,078 sec, 502,247 MBps, CPB=6,24

$ rhash --md5 -B                                                                                                                                                                        
RHash v1.3.6 benchmarking...                                                                                                                                                                                       
MD5 512 MiB calculated in 0,720 sec, 710,798 MBps                                                                                                                                                                  
MD5 512 MiB calculated in 0,719 sec, 711,943 MBps                                                                                                                                                                  
MD5 512 MiB calculated in 0,715 sec, 716,205 MBps                                                                                                                                                                  
MD5 512 MiB calculated in 0,711 sec, 719,896 MBps                                                                                                                                                                  
MD5 2048 MiB total in 2,866 sec, 714,692 MBps, CPB=4,45
```

... but real life says, with a 2,5GB iso, crc32 is more than 10 times faster.

```
$ rhash --crc32 -o checksum TrueOS-2017-07-05-x64-DVD.iso

$ rhash -c checksum --speed                                                                                                                                                      

--( Verifying checksum )--------------------------------------------------------
TrueOS-2017-07-05-x64-DVD.iso                       OK
Calculated in 5,057 sec, 504,94 MBps
--------------------------------------------------------------------------------
Everything OK

$ rhash --md5 -o checksum TrueOS-2017-07-05-x64-DVD.iso

$ rhash -c checksum --speed                                                                                                                                                        

--( Verifying checksum )--------------------------------------------------------
TrueOS-2017-07-05-x64-DVD.iso                       OK
Calculated in 62,630 sec, 40,77 MBps
--------------------------------------------------------------------------------
Everything OK
```

I don't know what to think. It must be faster now.

**Comment by rhash** [comment]
1. For benchmarking it's better to use statically linked rhash, to avoid loading librhash.so installed into the system:
~~~sh
./configure --enable-static && make build-static test-lib-static
~~~

2. When testing with a large file, you should take steps to avoid interference by OS file caching.

3. To check a hash file with a maximum speed, you should specify the hashsum by options (see #45):
~~~sh
rhash --check --crc32 --speed checksum.crc32
rhash --check --md5 --speed checksum.md5
~~~

Here are my benchmark results for GCC 7.3.0, arch=x64, Core i7 860 2.80GHz:
~~~
CRC32 2048 MiB total in 1,357 sec, 1509,764 MBps, CPB=1,66
MD5 2048 MiB total in 3,158 sec, 648,564 MBps, CPB=3,96
~~~

Hope, this help ;)

**Comment by noraj** [comment]
@rhash Noice thanks.
