### ISSUE TITLE
Please publish the GPG key used for signing

### ISSUE THREAD

**Issue by eli-schwartz** [rhash/RHash#50]
While git tags as well as the uploaded release archives appear to be signed, nowhere do you declare your GPG key so that packagers and users can actually make sure the key is in fact trusted. Preferably this would be listed in a separate location, e.g. the homepage at http://rhash.anz.ru/ (does not have SSL though :cry:).

Since the GPG key is not published, Arch Linux cannot add the *.asc signatures for verification of the source when building distro packages, as we cannot know which key to trust.

On the topic of GPG signing, would it be possible to sign each git commit in addition to each release tag? This can be done with `git commit --gpg-sign` (equivalent to `git tag -s `) or made the default using the config option `git config --global commit.gpgsign true` (equivalent to `git config --global tag.forcesignannotated true`).

This would allow users to verify the current git master when building development versions. For example, the [rhash-git](https://aur.archlinux.org/packages/rhash-git) package in the Arch User Repository would be able to verify the GPG signature of the commit used for building rhash, as soon as makepkg 5.1 is released which contains support for verifying git commits when building Arch Linux packages.

**Comment by rhash** [comment]
For now I've put the public key to the [Source Forge wiki page](https://sourceforge.net/p/rhash/wiki/PublicKey/).

**Comment by rhash** [comment]
Here is URL to download the public key: http://rhash.anz.ru/bin/rhash-public-key.asc

According to signing every commit. It would bloat the repository. Also it would required to use private key on each commit, and I just don't want it.
