### ISSUE TITLE
Support BLAKE2b & BLAKE2s

### ISSUE THREAD

**Issue by Skif-off** [rhash/RHash#52]
Возможно или, может быть, уже есть в планах?

**Comment by rhash** [comment]
See Issue https://github.com/rhash/RHash/issues/12

**Comment by Skif-off** [comment]
@rhash, прошу прощения, в фильтре вбил "blake" - результат быль 0 (сейчас проверил, с "blake**2** " находит, не ожидал) :(

**Comment by data-man** [comment]
@Skif-off 

Могу добавить поддержку BLAKE2 (и некоторых других), но, как я понимаю, автор не примет PR со сторонними библиотеками. :-)

**Comment by Skif-off** [comment]
@data-man 
Думаю, автора, можно понять - кроссплатформенно (Win, Linux, *BSD, MacOS) плюс лицензия. Сейчас глянул ради любопытства: исходники BLAKE2 доступны в т.ч. и под CC0 aka CC Zero, крайне лояльно, как и RHash, смущает только наличие ```ref/``` и ```sse/``` - определение автоматом как-то поинтереснее.

Библиотека сторонняя? У авторов не вижу библиотек, только исполняемые файлы вроде.

**Comment by data-man** [comment]
@Skif-off 

> Библиотека сторонняя?

От самих авторов :-) https://github.com/BLAKE2/libb2
> смущает только наличие ref/ и sse/ - определение автоматом как-то поинтереснее.

https://github.com/BLAKE2/libb2/blob/master/src/blake2-dispatch.c#L52

**Comment by rhash** [comment]
CC0 подходит. 

Blake2 довольно большое семество функций. Похоже, имеет смысл взять blake2b-512, т.к. большинство современых CPU  64-битные.

**Comment by Skif-off** [comment]
> Похоже, имеет смысл взять blake2b-512, т.к. большинство современых CPU 64-битные.

Но в случае чего, при необходимости, можно будет запустить и на 32-битной ОС?

Т.к. RHash - утилита универсальная, касательно инструкций SSE2 и далее: при всех плюсах хотелось бы сохранить возможность работать с RHash и на старых процессорах (по большей части AMD до Athlon 64, полагаю), если это будет возможно.

**Comment by data-man** [comment]
@Skif-off 
libb2 определяет поддержку необходимых инструкций процессором и динамически присваивает функции, наиболее эффективно реализующие алгоритм на этом процессоре.

**Comment by rhash** [comment]
@Skif-off, естественно)

**Comment by mrbluecoat** [comment]
I'm looking forward to this as well.  Impressive performance stats: https://blake2.net/

**Comment by Skif-off** [comment]
@rhash 
> Похоже, имеет смысл взять blake2b-512, т.к. большинство современых CPU 64-битные.

Если будет время и возможность, не могли бы вы рассмотреть и добавление BLAKE2**s**-256 заодно, если это не будет слишком уж геморрно?
Утилит толком и нет, из кросплатформенного вроде лишь `b2sum` и Double Commander...

**Comment by tankf33der** [comment]
[monocypher](https://github.com/LoupVaillant/Monocypher) имеет blake2b. Лицензия CC0.

**Comment by data-man** [comment]
[BLAKE3](https://github.com/BLAKE3-team/BLAKE3) уже давно на дворе. :)
[Есть](https://github.com/BLAKE3-team/BLAKE3/tree/master/c) C-реализация.
>This work is released into the public domain with CC0 1.0. Alternatively, it is
licensed under the Apache License 2.0.

**Comment by Skif-off** [comment]
> [BLAKE3](https://github.com/BLAKE3-team/BLAKE3) уже давно на дворе. :)

Давно - в смысле "полгода"? :) И все-все-все, поголовно, ну просто куда ни ткни, умеют BLAKE3 считать...

> [monocypher](https://github.com/LoupVaillant/Monocypher) имеет blake2b.

Не понял, как у неё с кроссплатформенностью, но главное - это библиотека, её не повесить на кнопку и в скрипте не запустить.
Правда, на странице загрузки выложены линки на биндинги для нескольких языков, но это ещё уметь надо...

**Comment by tankf33der** [comment]
> @data-man
> 
> > [BLAKE3](https://github.com/BLAKE3-team/BLAKE3) уже давно на дворе. :)
> 
> Давно - в смысле "полгода"? :) И все-все-все, поголовно, ну просто куда ни ткни, умеют BLAKE3 считать...
> 

blake3 ничего не привнес, только параллельность.

> @tankf33der
> 
> > [monocypher](https://github.com/LoupVaillant/Monocypher) имеет blake2b.
> 
> Не понял, как у неё с кроссплатформенностью, но главное - это библиотека, её не повесить на кнопку и в скрипте не запустить.
> Правда, на странице загрузки выложены линки на биндинги для нескольких языков, но это ещё уметь надо...

Monocypher работает на диапазоне 16бит (RL78) и выше, любая архитектура и ОС, например, IRIX.
Она проходит TIS (interp, CI) и CompCert (interp) и у нее был аудит (cure53) в этом году.

**Comment by rhash** [comment]
BLAKE2s and BLAKE2b hash functions were added by f693b9ec0db9a9d3150ef4ddc1566e319c763473, a479d7a4a6a997b7ee7e5f164e6b9d67868d196f and released in [v1.4.1](https://github.com/rhash/RHash/releases/tag/v1.4.1).

No SSE/AVX optimization were applied due to my lack of time (consider [donations](https://github.com/rhash/RHash/blob/master/docs/CONTRIBUTING.md), it will help).

For the BLAKE3 hash function please file another issue. Note, that Implementing another one hash function will also require significant change of librhash interfaces due to architecture limitation.
