### ISSUE TITLE
byte_order.c breaks if byte_order.h uses the bswap_32() fallback macro

### ISSUE THREAD

**Issue by Bloody2** [rhash/RHash#53]
Hello everyone,

If byte_order.h is run through __clang__ (in my case, clang++), the file concludes that if all else fails, the fallback macro shall be used:

#define bswap_32(x) ((((x) & 0xff000000) >> 24) | (((x) & 0x00ff0000) >>  8) | \
  (((x) & 0x0000ff00) <<  8) | (((x) & 0x000000ff) << 24))

Problem: byte_order.c contains code like:   bswap_32( *(src++) )

The above will accidently execute "*(src++)" multiple times as "x" in the fallback macro (instead of just once).

Also, to check if 32/64-bit bswap intrinsics can be used, tests like the following:

#elif (defined(__GNUC__)  && (__GNUC__ >= 4) && (__GNUC__ > 4 || __GNUC_MINOR__ >= 3))

should be expanded to simply check for __clang__ as well, like:

#elif defined(__clang__) || (defined(__GNUC__)  && (__GNUC__ >= 4) && (__GNUC__ > 4 || __GNUC_MINOR__ >= 3))

Luckily, you don't need bswap_16 which appeared in later clang versions, while 32/64-bit swappers were added early and can simply be assumed to be present as long as __clang__ is defined.

Other than that, your SHA/SHA3 sources compile & run just fine if compiled as C++ btw.

Great implementation - small, easy, nice & fast. Thank you very much!

**Comment by rhash** [comment]
Hello. The bug was fixed in release v1.3.5, please retest.

**Comment by Bloody2** [comment]
Confirmed. Sorry for the alarm, didn't notice that part has meanwhile changed, too.
Just one of those "rare bugs" that sometimes go unnoticed. Sorry again.
