### ISSUE TITLE
ключ --simple

### ISSUE THREAD

**Issue by grylem** [rhash/RHash#54]
Добрый день.
rhash -M testfile
сумма /ev_locker/testfile

rhash  -M --simple testfile
всёравно:
сумма /ev_locker/testfile вместо ожидаемого: "сумма testfile" 
Возможно я неверно понимаю значение ключа --simple?
MacOS Sierra.
Удачи.

**Comment by rhash** [comment]
The simple format is default for all hash sums except crc32, the later is printed in svf format by default.

Compare results of
_rhash -C testfile_
and
_rhash -C --simple testfile_
