### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by JPeterMugaas** [rhash/RHash#59]
For some reason, I sometimes will get a compile error with Rhash.  Using the configure script, I something get a message about "Device or resource" busy and than I get errors about linking to GetText.  that was attempting that configure script "fix"

==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Checking for target OS ... MINGW32
Checking for cc version ... 7.3.0
Checking for linker support for -static ... yes
Checking for linker support for --version-script ... yes
Checking for linker support for --nxcompat --no-seh --dynamicbase ... yes
Checking for gettext ... ./configure: line 286: /tmp/rhash-configure-29544-80132/tmp.c: Device or resource busy
./configure: line 321: /tmp/rhash-configure-29544-80132/tmp.c: Device or resource busy
found
Checking for OpenSSL ... ./configure: line 310: /tmp/rhash-configure-29544-80132/tmp.c: Device or resource busy
./configure: line 312: /tmp/rhash-configure-29544-80132/tmp.c: Device or resource busy
./configure: line 312: /tmp/rhash-configure-29544-80132/tmp.c: Device or resource busy
./configure: line 312: /tmp/rhash-configure-29544-80132/tmp.c: Device or resource busy
./configure: line 312: /tmp/rhash-configure-29544-80132/tmp.c: Device or resource busy
./configure: line 312: /tmp/rhash-configure-29544-80132/tmp.c: Device or resource busy
./configure: line 315: /tmp/rhash-configure-29544-80132/tmp.c: Device or resource busy
runtime
Checking for sources ... RHash 1.3.5
Writing config.mak
Writing librhash/config.mak
Writing dist/librhash.pc
cc -c -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  calc_sums.c -o calc_sums.o
cc -c -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  hash_print.c -o hash_print.o
cc -c -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  common_func.c -o common_func.o
cc -c -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  hash_update.c -o hash_update.o
cc -c -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  file_mask.c -o file_mask.o
cc -c -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  file_set.c -o file_set.o
cc -c -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  find_file.c -o find_file.o
cc -c -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  hash_check.c -o hash_check.o
cc -c -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  output.c -o output.o
cc -c -DSYSCONFDIR=\"/mingw32/etc\" -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  parse_cmdline.c -o parse_cmdline.o
cc -c -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  rhash_main.c -o rhash_main.o
cc -c -DUSE_GETTEXT -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  win_utils.c -o win_utils.o
cd librhash && make lib-shared
cd librhash && make lib-static
make[1]: Entering directory '/home/jpmugaas/exp/mingw-w64-rhash-git/src/build-i686/librhash'
sed -ne '1s/.*/{ global:/p; s/^RHASH_API.* \(rhash_[a-z0-9_]*\)(.*/  \1;/p; $s/.*/local: *; };/p' rhash.h rhash_torrent.h  > exports.sym
cc -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  -DRHASH_EXPORTS algorithms.c byte_order.c plug_openssl.c rhash.c rhash_timing.c rhash_torrent.c aich.c crc32.c ed2k.c edonr.c hex.c md4.c md5.c sha1.c sha256.c sha512.c sha3.c ripemd-160.c gost.c has160.c snefru.c tiger.c tiger_sbox.c tth.c torrent.c whirlpool.c whirlpool_sbox.c -Wl,--nxcompat,--no-seh,--dynamicbase  -shared -Wl,--out-implib=librhash.dll.a,--version-script,exports.sym,--output-def,librhash.def -o librhash.dll
make[1]: Entering directory '/home/jpmugaas/exp/mingw-w64-rhash-git/src/build-i686/librhash'
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  algorithms.c -o algorithms.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  byte_order.c -o byte_order.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  plug_openssl.c -o plug_openssl.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  rhash.c -o rhash.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  rhash_timing.c -o rhash_timing.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  rhash_torrent.c -o rhash_torrent.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  aich.c -o aich.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  crc32.c -o crc32.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  ed2k.c -o ed2k.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  edonr.c -o edonr.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  hex.c -o hex.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  md4.c -o md4.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  md5.c -o md5.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  sha1.c -o sha1.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  sha256.c -o sha256.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  sha512.c -o sha512.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  sha3.c -o sha3.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  ripemd-160.c -o ripemd-160.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  gost.c -o gost.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  has160.c -o has160.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  snefru.c -o snefru.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  tiger.c -o tiger.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  tiger_sbox.c -o tiger_sbox.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  tth.c -o tth.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  torrent.c -o torrent.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  whirlpool.c -o whirlpool.o
cc -c -DOPENSSL_RUNTIME -O2 -pipe -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -W -Wstrict-prototypes -Wnested-externs -Winline -Wpointer-arith -Wbad-function-cast -Wmissing-prototypes -Wmissing-declarations  whirlpool_sbox.c -o whirlpool_sbox.o
ar cqs librhash.a algorithms.o byte_order.o plug_openssl.o rhash.o rhash_timing.o rhash_torrent.o aich.o crc32.o ed2k.o edonr.o hex.o md4.o md5.o sha1.o sha256.o sha512.o sha3.o ripemd-160.o gost.o has160.o snefru.o tiger.o tiger_sbox.o tth.o torrent.o whirlpool.o whirlpool_sbox.o
make[1]: Leaving directory '/home/jpmugaas/exp/mingw-w64-rhash-git/src/build-i686/librhash'
make[1]: Leaving directory '/home/jpmugaas/exp/mingw-w64-rhash-git/src/build-i686/librhash'
cc calc_sums.o hash_print.o common_func.o hash_update.o file_mask.o file_set.o find_file.o hash_check.o output.o parse_cmdline.o rhash_main.o win_utils.o librhash/librhash.dll -Wl,--nxcompat,--no-seh,--dynamicbase   -o rhash.exe
calc_sums.o:calc_sums.c:(.text$rename_file_by_embeding_crc32+0x194): undefined reference to `libintl_gettext'
calc_sums.o:calc_sums.c:(.text$rename_file_by_embeding_crc32+0x212): undefined reference to `libintl_gettext'
calc_sums.o:calc_sums.c:(.text$save_torrent_to+0x106): undefined reference to `libintl_gettext'
calc_sums.o:calc_sums.c:(.text$check_hash_file+0xd2): undefined reference to `libintl_gettext'
calc_sums.o:calc_sums.c:(.text$check_hash_file+0x5ee): undefined reference to `libintl_gettext'
calc_sums.o:calc_sums.c:(.text$check_hash_file+0x63d): more undefined references to `libintl_gettext' follow
parse_cmdline.o:parse_cmdline.c:(.text$print_help+0x24): undefined reference to `libintl_sprintf'
parse_cmdline.o:parse_cmdline.c:(.text$print_help+0x30): undefined reference to `libintl_gettext'
parse_cmdline.o:parse_cmdline.c:(.text$print_help+0x65): undefined reference to `libintl_gettext'
parse_cmdline.o:parse_cmdline.c:(.text$print_help+0x82): undefined reference to `libintl_gettext'
parse_cmdline.o:parse_cmdline.c:(.text$print_help+0xaf): undefined reference to `libintl_gettext'
parse_cmdline.o:parse_cmdline.c:(.text$print_help+0xdc): undefined reference to `libintl_gettext'
parse_cmdline.o:parse_cmdline.c:(.text$print_help+0x109): more undefined references to `libintl_gettext' follow
parse_cmdline.o:parse_cmdline.c:(.text$print_version+0x24): undefined reference to `libintl_sprintf'
parse_cmdline.o:parse_cmdline.c:(.text$read_options+0x3e8): undefined reference to `libintl_gettext'
parse_cmdline.o:parse_cmdline.c:(.text$read_options+0x463): undefined reference to `libintl_gettext'
parse_cmdline.o:parse_cmdline.c:(.text$read_options+0x812): undefined reference to `libintl_gettext'
parse_cmdline.o:parse_cmdline.c:(.text$read_options+0x8f8): undefined reference to `libintl_gettext'
parse_cmdline.o:parse_cmdline.c:(.text$read_options+0xa98): undefined reference to `libintl_gettext'
rhash_main.o:rhash_main.c:(.text$load_printf_template+0xfb): more undefined references to `libintl_gettext' follow
rhash_main.o:rhash_main.c:(.text.startup.main+0x7a): undefined reference to `libintl_setlocale'
rhash_main.o:rhash_main.c:(.text.startup.main+0x8e): undefined reference to `libintl_bindtextdomain'
rhash_main.o:rhash_main.c:(.text.startup.main+0x9f): undefined reference to `libintl_textdomain'
rhash_main.o:rhash_main.c:(.text.startup.main+0x132): undefined reference to `libintl_gettext'
rhash_main.o:rhash_main.c:(.text.startup.main+0x32b): undefined reference to `libintl_gettext'
rhash_main.o:rhash_main.c:(.text.startup.main+0x368): undefined reference to `libintl_gettext'
rhash_main.o:rhash_main.c:(.text.startup.main+0x413): undefined reference to `libintl_gettext'
win_utils.o:win_utils.c:(.text$setup_console+0x34): undefined reference to `libintl_setlocale'
win_utils.o:win_utils.c:(.text$setup_console+0x96): undefined reference to `libintl_bind_textdomain_codeset'
win_utils.o:win_utils.c:(.text$setup_locale_dir+0xeb): undefined reference to `libintl_bindtextdomain'
win_utils.o:win_utils.c:(.text$win_vfprintf+0x58): undefined reference to `libintl_vsnprintf'
win_utils.o:win_utils.c:(.text$win_vfprintf+0xb4): undefined reference to `libintl_vfprintf'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:158: rhash.exe] Error 1

**Comment by rhash** [comment]
I believe this is because Windows locks openned files and some of gcc processes are still running (with not closed files) after gcc exited. So it should be a gcc bug.

This issue possibly apperared after I added passing of gcc "-c" option in the cc_check_headers() function. Also possible cause is gcc '-pipe' option, and you see the bug more often because configure now contains more gcc tests.

We should indentify the culprit, and check what gcc options make the bug dessapear.
Possible workaround can be allocating new filenames for every gcc test, but this will complicate the script. I would vote for finding the minimal testcase, and then passing the bug to the mingw team.

**Comment by rhash** [comment]
Help wanted with researching the cause.

**Comment by rhash** [comment]
Can't reproduce
