### ISSUE TITLE
rhash.c:448]: (error) Resource leak: fd

### ISSUE THREAD

**Issue by dcb314** [rhash/RHash#60]
Source code is

   if ((fd = fopen(filepath, "rb")) == NULL) return -1;

    if ((ctx = rhash_init(hash_id)) == NULL) return -1;

Suggest add call to fclose( fd) inside last if.

**Comment by rhash** [comment]
Thanks!
Fixed by 8c332d48ec39dccf52d809cbac5673675f94533a.

**Comment by rhash** [comment]
The fix is included into RHash v1.3.6.
