### ISSUE TITLE
Installing shared library doesn't install headers

### ISSUE THREAD

**Issue by kyrias** [rhash/RHash#66]
Only the static library install target actually installs the headers.

**Comment by kyrias** [comment]
Looking closer, `make install` also doesn't install the .so symlink.)

**Comment by rhash** [comment]
It's done on purpose. Sometime you need to install LibRHash shared library without headers and the symlinks. But static library is installed, when you want to compile something, and you obviously will need also headers and the symlink.

The .so symlink can be installed by command `make install install-lib-so-link`.

Headers can be installed by `make -C librhash install-headers`.

**Comment by kyrias** [comment]
It feels like if you actually need that it's simpler to just delete the files after the fact than having a non-standard and undocumented way to fully install something.

**Comment by rhash** [comment]
Ok, provide a link to a commonly accepted standard document and I change the installation behaviour.

**Comment by rhash** [comment]
I've updated Makefile. Now one can install library and headers using command:
~~~
make install install-lib-so-link install-lib-headers
~~~
