### ISSUE TITLE
excluding one folder

### ISSUE THREAD

**Issue by splaisan** [rhash/RHash#77]
As from [#9](https://github.com/rhash/RHash/issues/9), could you please provide a find piping example command to exclude the folder donotinclude in a situation like below but processing all the rest recursively. I have tried find but could not make it to exclude it because of -r

> Top
> --file1
> --file2
> --subfolder1
> --subfolder2
> --donotinclude

The --exclude is only for file types and excluding folders would really be nice to have

my curren tcommand for full rhash 

rhash -Mr Top -o myhash.md5

**Comment by rhash** [comment]
You should construct file list with `find` command and pass it to rhash:
~~~bash
find Top -type f -not -regex '.*/donotinclude/.*' > /tmp/file-list.txt && rhash -M --file-list /tmp/file-list.txt
~~~

**Comment by rhash** [comment]
Recently I fixed a bug with reading a file-list from standard input.

After the commit b8514dd1793eb8b827f88285613f619ae8ae8780 you can use a shorter command:
~~~sh
find Top -type f -not -regex '.*/donotinclude/.*' | rhash -M --file-list -
~~~

**Comment by splaisan** [comment]
Thanks you very much for this nice feature and example,  now I can use rhash for my data checkup
cheers

**Comment by i2324561w2** [comment]
Sorry, I don't know if I should have opened another issue or not.
I don't think it exists a similar command as "find" in Windows, also this way I can't use a relative path, so can you please think again about it?

**Comment by satori80** [comment]
I've been thinking the same thing for a while now.

**Comment by satori80** [comment]
@2324561w2, I've been thinking the same thing for a while now.

**Comment by rhash** [comment]
With RHash version 1.4.1 or higher, use Windows DIR and FINDSTR commands:
~~~bat
dir /S /B "C:\THE_FOLDER_TO_SEARCH" | findstr /V /I /C:"\\SOME_SUBFOLDER\\" | rhash -M --file-list -
~~~
The `\\` sequence in the `findstr` `/C:` parameter represents character `\`. Actually any special character of `\.*^$[]` must be escaped by `\`. Check the `help findstr` output.

**Comment by satori80** [comment]
The findstr solution only seems to work for 1 directory.

**Comment by satori80** [comment]
The ```--file-list -``` option doesn't seem to allow for "special" characters: 
```
echo "“Trials And Tribble-ations”. An Historic Endeavor.mkv" | rhash -H --file-list -
RHash: ""Trials And Tribble-ations". An Historic Endeavor.mkv" : No such file or directory
```

So, is this a bug in ```--file-list -```, because ```rhash -H "“Trials And Tribble-ations”. An Historic Endeavor.mkv"``` works fine.
