### ISSUE TITLE
Support base58

### ISSUE THREAD

**Issue by Kcchouette** [rhash/RHash#80]
See https://en.wikipedia.org/wiki/Base58

As supporting #79 + this one (base 58) we can recreate ipfs hash and bitcoin hash
Thank you

**Comment by rhash** [comment]
Hello, we will not support Base58, cause it is not unambiguously specified. Also, the related feature #79 is already got rejected.

As a workaround, I propose you to write a python script, using LibRHash [bindings](https://github.com/rhash/RHash/tree/master/bindings/python).
