### ISSUE TITLE
rhash --bsd

### ISSUE THREAD

**Issue by grylem** [rhash/RHash#82]
Добрый день.
при использовании ключа --bsd на macOS получается разница в два пробела
при помощи rhash
MD5   (rhash.1) = 6c2ec3b7b9bf61b26a9ce6557a66641d
при помощи стандартной для macOS md5
MD5 (rhash.1) = 6c2ec3b7b9bf61b26a9ce6557a66641d

Возможно ли добавить настройку поиска файла конфигурации rhashrc в /usr/local/etc ?
Возможно ли добавить опцию показывать только имя файла без полного пути к нему?
Спасибо.
[out.txt](https://github.com/rhash/RHash/files/2872730/out.txt)

**Comment by rhash** [comment]
День добрый.
Пробелы добавлены, чтобы красивее был вывод `rhash --all --bsd FILE'.
Для поиска конфига в /usr/local/etc надо пересобрать программу с опцией:
./configure --sysconfdir=/usr/local/etc

Для печати имени вместо пути подходит опция --printf (см. manual):
rhash --printf='MD5 (%f) = %m\n' rhash.1

  С наилучшими,
  Алексей

**Comment by grylem** [comment]
Алексей,
огромное спасибо за помощь и разъяснения(не говоря уж, о самой программе)
Удачи.

**Comment by rhash** [comment]
@grylem, there was a bug with sysconfdir, it's fixed by 2b204b077a812fc89b135c0ea24a7a2daea82a6a.
