### ISSUE TITLE
Output checksums in base64 notation

### ISSUE THREAD

**Issue by grylem** [rhash/RHash#83]
Добрый день.
Можете добавить вывод суммы в base64 как у OpenBSD md5/sha с ключом -b ?
пример:
sha256 rhash_main.h
SHA256 (rhash_main.h) = d55699cdc06410743a62d94300c1de29cd7433eea862037473367904b64f1c7a

sha256 -b rhash_main.h
SHA256 (rhash_main.h) = 1VaZzcBkEHQ6YtlDAMHeKc10M+6oYgN0czZ5BLZPHHo=
Спасибо..

**Comment by rhash** [comment]
Hello,
the option -b/--base64, as well as --base32 and --hex is supported by commit 6173613b3a1a4dc93a2e1178ac972d25cde294ac.

Another commit ac4e04ffe249f32354294a7c08e09557a783fe10 supports verification of base32/base64 formatted hash sums.

**Comment by grylem** [comment]
Алексей, спасибо большое.
Но проверка для base32/base64(как и без) с ключом --bsd осталась для sha1, не могли бы вы добавить проверку для sha256, sha1 используется сейчас все реже и реже.

**Comment by rhash** [comment]
Fixed by 0374d81c57428f90589f9f805a5733d14c668bce.
