### ISSUE TITLE
format of %{mtime}

### ISSUE THREAD

**Issue by wilfz** [rhash/RHash#84]
rhash's printf option is great for putting out file related metadata in tailor made format.
But I wonder about the very  unusual datetime format of %{mtime} with the seconds separated by '.' instead of ':'
At first I thought about adressing this as a bugfix issue but there are probably already too many scripts out in the field relying on this format.
So I suggest a new format option %{mdatetime} to format the modification time in ansi format YYYY-MM-DD hh:nn:ss.
This would ease sorting or importing the output with other programs.
I built it for myself on windows and raspbian and would like to make it available to the public.

**Comment by rhash** [comment]
Just changed %{mtime} format toYYYY-MM-DD hh:mm:ss  by the commit 657825709a7711538d9a19120a990ba5120780fb.

SFV file header will still use the old format.

**Comment by rhash** [comment]
The change is included in v1.3.9.
