### ISSUE TITLE
Symlinks On Command Line are not properly handled

### ISSUE THREAD

**Issue by rbiro** [rhash/RHash#85]
If you put a symlink to a directory on the command line, you get an error that cd is a directory with or without a --follow.

$ ln -sfn ../cd .
$ ls -l cd
lrwxrwxrwx 1 rossb rossb 5 Mar 15 18:25 cd -> ../cd
$ LD_LIBRARY_PATH=./librhash ./rhash -rH cd
RHash: cd: Is a directory
$ LD_LIBRARY_PATH=./librhash ./rhash -rH --follow cd
RHash: cd: Is a directory
$ LD_LIBRARY_PATH=./librhash ./rhash -rH .
bc917ce0e081735c01728133a48a46c1d5a48923  rhash_main.o
4ed87fa2ec2d0fd2affd6cfc4390939b76b5dbd8  file_set.c
a7434dbacc8143300a5146ab7ea4c824a80f85f0  file_mask.o
4d8ee914797403697cbeeeb909a8cc89df6180e5  win_utils.o
303f069d67b088ee3e17ace3a8dade2f4f1a3e25  output.h
33081a23d4a9bce741cf8f407a3abf22f4cb57fa  parse_cmdline.c
d909fbe107090592748d29fe23cfdfa6984349de  win_utils.h
b2df47fe3b662b65bc44df1a5fba7b6ac64b2b40  parse_cmdline.h
4e39bc95082097d09fa7c31a53abd0b7035aede9  file.o
83f80601b6da9999ffa614b725aef957d96da443  file.c
2fb040ee1cbd76002cc64da8277fe05e75971b7e  common_func.c
4099162c37b6197e73b6e9adbd169ff886358a12  .gitignore
c776a1ce0e735d30d3cccec8923e289da5a3b6bd  version.h
856af1419e8ad391089dabf2e58734661aabd5d4  win_utils.c
c92ccec293069a6362da8ce749186e6d2a400129  common_func.o
9db1e194d33a281093308f3780581abff6942edb  hash_update.c
0a689fb8d8ef522c484e3d46f11a6b061b138935  parse_cmdline.o
2750f9850af082c1eec1dd93f74da6fce2544b76  INSTALL.md
15ff691f11129b0511ba122a728ddece11aaef29  platform.h
1b6eee83f9e302f145e6fce4af9505379dcb3c67  hash_check.o
ec1af1e52ce75c28242b86a095cc779a4ac99df5  file_mask.c
50aa3a8f4191551e1a81c7690ede1da6b4939f51  COPYING
e16334e5687553acce46ea1c9a2432bc54e32237  calc_sums.h
571aba63df2868a4cc25ab8268a9f0ee3c4f6e6e  README.md
57dc82a8b92348c7c88ab0c7403cdade18c932a5  hash_print.h
ad7798129d179fddff3e0888c24d44813dd2a05b  hash_check.c
203df4348e61b8e4a1277fca35bd132679fae727  calc_sums.c
ac1b87b23e1850275ebf9c193e97d1e1ce58aa8d  common_func.h
0f2f26493c9d681397beb550f71a406a4efa3b4b  rhash
942b49a7f90fc1dc40baa728fc8f1f0cab19d3bf  find_file.h
fd966f4f47c33424fa5a96e9ebe110b73b057f5d  config.mak
2953c753321788c8f45e4de0489dd2337b255f30  file_set.h
f9ab482f580ff4b0c020e6ae186c8273e0b40d37  ChangeLog
8414a093e484aa0b6ec76da732e153fa778e1784  file_set.o
ff08b596a462593d30a7b29f7afd5ab88c645f42  output.c
ed8b1b993a62d0461ea380ede5ef34403f4889ef  hash_update.o
f293fb51ab1b41f96450f7b7c1286e311a89bd93  Makefile
b9d4bc1c18220d50fa3cf036d95029324c288b91  rhash_main.h
8bc7f7dbf5042b93b4e68a8b9fcd08edbca1d611  config.log
59dbc311a5fcd77b3e5f9df72375d5c3d677c891  hash_print.o
58c7902f9aa87d430d5cc9ca50829b244ba7c1f1  find_file.c
3db8ba6f691b0135f8df1f591c21c3642323d865  hash_check.h
f9537933d4d11c1f15e716a966820724a7c89b1a  file_mask.h
d0d5a5a56d7dacc739fc979bf68fa2e6d2692012  file.h
44885b4b0c6933f5960f882ac9828c79404c6588  hash_print.c
4647ff7dae3d704626c3782ed02438e19d1e6c35  rhash_main.c
b51e43b334511ddb526540d9c129d840f55ce460  output.o
2a1066de1edcd762cddcf0d270dad456d51a1342  calc_sums.o
abb52eedaf3c44eedfe783d8080c298ec861325b  configure
9eb8c8b0202a6516b15fd0fe91e148a3490d00b9  find_file.o
52fc0fdc45fcced2a6e70e7549dd582f0d0a8026  hash_update.h
becbf32c55d6e1ff43fcd2586a7198a8062e0844  po/fr.po
f2fb2e95a3c64ae44042fe9a56ef224da322cbfe  po/ro.po
18134bfb0a27b1bddac28e84cc196a556c519b84  po/de.po
730b8c0d1561489f6681beb49682795ab5a542eb  po/it.po
e1a7aa6e54d2690a095af9905d7daebd6f26ad5e  po/rhash.pot
c5797bfa160b923dec736b0e409edf5081314702  po/en_AU.po
474c0f7007a613a881dbb3ab69d2353e3a837e3d  po/ru.po
04cc2ed25929d4b117251e871cc3994c6a193e49  po/ca.po
3319a55cf666200f9b173264c849010484ba2b6f  po/es.po
df4bbc54a0256c9d24181b9e55a7f2dd98634a28  po/gl.po
536a32297f564b7e03dff1cf3d0589df5cf495b0  dist/rhashrc.sample
6e74be4810ef6b60197ef95baacf96cf8abf4327  dist/rhash.1
57aea89a1b284263d502c6180689d635ccb3899a  dist/librhash.pc
85adcaa8574c027becdc3a66f4b8d9fd7264dd61  dist/rhash.1.win.sed
fcf0aba73d0bd745b4bcc422d1422540df2f26aa  dist/magnet.bat
3c5495a761a9072f56164656295b2db522ee80f8  dist/rhash.spec.in
b71801cf8bcdf205400a4a68c9c81a29d94963c8  dist/MD5.bat
cb7c2bda3ed52eb8668b83b499898e595e7fb2a2  tests/test_rhash.sh
5b00669c480d5cffbdfa8bdba99561160f2d1b77  tests/test1K.data
ce4aec1f84342703c715aa07027fc14e68fa4749  docs/LIBRHASH.md
45001145ce398bd23697151d2243e3a4cd4fb6dc  docs/CONTRIBUTING.md
63fcfb6d381fe622c9ef720deabfed72410eb95d  librhash/whirlpool_sbox.c
11119814f82f9f9dc56312715e6b63bcdd507385  librhash/hex.h
02304c428035622ac344b1bac5ceaa08ab1ec1d7  librhash/gost94.c
194908dd71c686a93554ce8c59f8c41c9ed99b27  librhash/sha3.c
f39c3a3654fc565ef070809581a626850e3ac86f  librhash/rhash_timing.c
8ebc0124cae5c4ebb09134d3f70dc8240c92629b  librhash/ustd.h
7adae4cdec0015ae1f43a21052066d24d11c3545  librhash/crc32.h
eb4c0023563538983a49310975b10de5f3b10af3  librhash/gost12.c
131ea0c51a587e6e86c3f12e33d386f9e962c53a  librhash/snefru.h
fb07c524dc1f41348daaa560395164aefde47de4  librhash/torrent.c
09666355d8581191cd262672d92758ff5ace48e1  librhash/rhash_torrent.c
06682bf46fb24874f71dadd476e8c2351d9dc619  librhash/rhash_torrent.h
a03e6a8d16bde3e7ea2f1c7eb994384593fc6595  librhash/rhash.h
5349c577c6f59dedc6d8dabb4c2dc5f0640585b1  librhash/plug_openssl.h
67e3e1260e0222c7ef584bfc0da5ce6fa868cb75  librhash/md5.c
d1f40be2781cb2a7a2cc2ea2a715e6c837d4a3b9  librhash/md4.c
804d715cd4d6f8bbae58c994eb92236b28808908  librhash/has160.c
b5299aeb56d6a3b185865bcc1cb5641337dd8323  librhash/sha256.c
deb675353b92f0ff0e6dc474232a74a6443bd4d9  librhash/test_hashes.c
ea161d874f2126e28c93c90ad3a904f40d92dda8  librhash/snefru.c
f66adca8d6c442db587b601b9f10847d60e0a2d4  librhash/edonr.c
9fb348d905202510fef6733acb742e315d568ea4  librhash/sha512.h
9ac34fb330e86f82a4c97079fa678a44fb8cc8fe  librhash/ed2k.h
53a2bf16eb9bb4c908a4fb69766dfc73c2a61ef6  librhash/sha3.h
c5770ecda0b1823b15e32b21909a164220e9c167  librhash/algorithms.c
147638da94267f4c9ad9244e9f9dae6a9de86c8b  librhash/sha512.c
9c684e81d28336872ebe51b169755a50ac94fdd2  librhash/Doxyfile
f4a5d9a79567c41c8a1d185b7ce196070b76e150  librhash/edonr.h
df33669e65c27bdeb08c23488d62140b683887ac  librhash/util.h
262cb2bb195604c1ac680524fa09971239711a5d  librhash/byte_order.c
1be9ea4fd37dcd4a48953264ab2ecfc08ff1ebe7  librhash/hex.c
b0fdda00d31ead885593ff8079a7dd6395b1f907  librhash/exports.sym
8f8c488af33baab25fd77525e1626ae7e8c9a786  librhash/whirlpool.h
a7af727874e90f137040de30a70e71577148ee02  librhash/byte_order.h
83753ada28e3d38d06836afe31da815bc93d9d39  librhash/tiger_sbox.c
c9eec2717d12066730bb6402fe23ba64d3821a14  librhash/ripemd-160.c
dc2196c9ab07b78477b2e0fd340901c36bcb2b90  librhash/test_hashes.h
c1693a11c2210728e8f16318f1fcbce45088139a  librhash/ed2k.c
f900da9fcbeb6ef1a1f22c8630ff046611b99f79  librhash/config.mak
077b0e7105896c82aac8840bd24acbc04ecff3fe  librhash/md5.h
269e65449ebb2bd98846ca31e9c26f9e29f85868  librhash/aich.c
58f9d1dcef78dc72bbdbd13f37391d4dc31828bc  librhash/sha1.c
9d9d0f19616ce960c2171aaa7a492f19fff730a5  librhash/tth.h
77c73d514e4c9d507966790dbee1746cc7603b25  librhash/tth.c
b4130c06d8550bc0c61198c17ed498dde13fa28a  librhash/algorithms.h
718016fb132b358152d6f7425f4ea82be0c83fd8  librhash/gost12.h
965d900efb3eac66bcae7950af630a27c3891ae3  librhash/Makefile
4a6773c37e7e6c19068080f5ec84e751513cf5e8  librhash/torrent.h
5743b64a9d783d6d2486b53148c09f5fc63406b4  librhash/sha1.h
f5cfcb40d9d71d1488edf8f3063dedb8762b60be  librhash/whirlpool.c
089c7d250e3f9be5830aaec00eb9dd181f0fa14b  librhash/sha256.h
86f3d173bdbc38dac3d28a247cedd45468c5ebf0  librhash/tiger.c
17110ad8587a3879a63bd9019e9650ef265f4b62  librhash/rhash_timing.h
b00dde8b379e40ceab64f72945663fd3afe09041  librhash/rhash.c
23cec3f3a09ac8eb71f821d7e96dd551b828d439  librhash/librhash.so.0
1164a08bc5342295c3e29f8456bb82bcf6397961  librhash/plug_openssl.c
f03f1f9d32fcf7126bf8899ebc6c414fb21bcbff  librhash/gost94.h
19147d6d3b07162c318a52bc3c68c7b5d2ab2133  librhash/tiger.h
d37259a725c256ecdd0d475025bff43fb0ef08b9  librhash/crc32.c
945cf2b09258dc36f7327c307e3ea1d0a30176e8  librhash/ripemd-160.h
b528b5772acba1e1bd16550924450214c63aad8d  librhash/aich.h
f8d4e55fa5b097e44eeb149bf188a23f8f08450c  librhash/md4.h
889391a4a31edc44c3abcb3307c034ae6b37ef35  librhash/has160.h
acbaef275e46a7f14c1ef456fff2c8bbe8c84724  .git/HEAD
b90b4a897ed941caba5879a8525783baecb32bf2  .git/packed-refs
9a27bc6ca51feb22ba8e287c55110030735554bf  .git/config
d3a172ca8406f875ad6bad4ab54b50d60449bb2b  .git/index
9635f1b7e12c045212819dd934d809ef07efa2f4  .git/description
21e4fd30d6afeff4ca1d9dfc989f44d0e56acd9b  .git/logs/HEAD
21e4fd30d6afeff4ca1d9dfc989f44d0e56acd9b  .git/logs/refs/remotes/origin/HEAD
21e4fd30d6afeff4ca1d9dfc989f44d0e56acd9b  .git/logs/refs/heads/master
d9427cda09aba1cdde5c69c2b13c905bddb0bc51  .git/refs/remotes/origin/HEAD
b4c6332d14ef79742e3986372f863bd4c4e91be2  .git/refs/heads/master
705a17d259e7896f0082fe2e9f2c0c3b127be5ac  .git/hooks/pre-receive.sample
b614c2f63da7dca9f1db2e7ade61ef30448fc96c  .git/hooks/post-update.sample
5c8518bfd1d1d3d2c1a7194994c0a16d8a313a41  .git/hooks/pre-push.sample
e729cd61b27c128951d139de8e7c63d1a3758dde  .git/hooks/update.sample
18be3eb275c1decd3614e139f5a311b75f1b0ab8  .git/hooks/pre-rebase.sample
f208287c1a92525de9f5462e905a9d31de1e2d75  .git/hooks/pre-applypatch.sample
36aed8976dcc08b5076844f0ec645b18bc37758f  .git/hooks/pre-commit.sample
4de88eb95a5e93fd27e78b5fb3b5231a8d8917dd  .git/hooks/applypatch-msg.sample
2b6275eda365cad50d167fe3a387c9bc9fedd54f  .git/hooks/prepare-commit-msg.sample
ee1ed5aad98a435f2020b6de35c173b75d9affac  .git/hooks/commit-msg.sample
7e9ed8b3cebca7ac832552ebea97b812af88662d  .git/objects/pack/pack-91ef04d58faef8a47f6fcd9acf9bf9a5a57e5b25.idx
f022acda804e1866f680db5c8f307d602dc6a9bd  .git/objects/pack/pack-91ef04d58faef8a47f6fcd9acf9bf9a5a57e5b25.pack
c879df015d97615050afa7b9641e3352a1e701ac  .git/info/exclude
efb88f8b1721520156db40917a11c6a178294d03  build/vc-2010/rhash.vcxproj
f18ee9648a7c93ce598482b62a985db40990ba6f  bindings/COPYING
8f7f3ffd4ba964de5fc6922f81e003dd290f32c2  bindings/ChangeLog
3311bc3c82a197bbdbcd3122efa51449df477e55  bindings/version.properties
30207aa5f339fbfe3537f6e53598161d1615534a  bindings/Makefile
d6b2e9f7c91ec9a5e06f830f7a24b5e8d56a525d  bindings/python/test_rhash.py
b0acf915c54d2c6ef53be580ed2045225a3b02d8  bindings/python/.gitignore
95534a7124d602a92b958ede2cfeca29f2d4ef8a  bindings/python/rhash.py
8256c8f7a44f8d231ed781d41274feba903792a9  bindings/ruby/.gitignore
4a34d631dcf46d80424c775cbc54d837a9970b21  bindings/ruby/test_rhash.rb
59628b66cb14b9a9a89ce088d255fb892f29c6ae  bindings/ruby/extconf.rb
191a400d1f0458cac811ce0684ccc5ebaaf47015  bindings/ruby/rhash.c
9330101e44c2126334884d17333bc3c5a05fa389  bindings/perl/META.json
863566dce283fb04e0271c750bd1cc538fbc5157  bindings/perl/Makefile.PL
221d15c85de6d8896c46f49e10c5df5f5341b165  bindings/perl/MANIFEST
8028b8ed1b271fe7a360c0572a66bcfa2aff80df  bindings/perl/README
93be51090b47802586ca7060e8f88c4f15104cb3  bindings/perl/.gitignore
5e82bafd6b2023fcc5d18d5bd65c0dfa9a951564  bindings/perl/Rhash.pm
1dcf088a3b915dba4f94eb4a194ea24086424088  bindings/perl/META.yml
79b2da6c17fee5f73084a552e4c6acb2ea408867  bindings/perl/Rhash.xs
df02dd7f0652cd0f5c56236588ae994b4bb7046e  bindings/perl/typemap
72bc0cc99a565d36aeca8faf6d9c19df4bb73b99  bindings/perl/t/3test_all_hash_functions.t
fea506a1321936277e2a3441e8bab2cae7b056ad  bindings/perl/t/1test_hash_calculation.t
5e178d3989308adfd74b2f43ca24a4189474db2e  bindings/perl/t/2test_static_functions.t
438875b6aad1b01767f78e951aff6f54432be17d  bindings/php/config.m4
25c2c28792b110ca4f99ee5c47231979ad3d6fa2  bindings/php/php_rhash.h
05aa47c5cbbaa664ece03e5b23554e1d7b177cfe  bindings/php/php_rhash.c
f28d1c341b69ce9ad1bb9d21da3b65b49ad8b8dd  bindings/php/php_compatibility.h
3860fdac2388ab096f31a50a29a8d15c3288edc4  bindings/php/tests/003.phpt
847b829847f734ad108a141ee921e239e7e011f6  bindings/php/tests/001.phpt
11b6c7eca386f5bb5c81ee00ea1ab31f34b9bdf1  bindings/php/tests/002.phpt
eecb5f47705e09217b7c1895bea491d0b5f94ec6  bindings/java/.gitignore
41d7a8573b06b44ed2500a058c6d3c8221a91c6c  bindings/java/Makefile
5d73762e57bbf27fb80b1a9c89ad133307fec3bc  bindings/java/native/bindings.c
51337c1ec02db72ed4bf54235381ada85c07cb8d  bindings/java/native/digest.c
91eb7965062f4312de0c32613b15f5a8ef33a9d7  bindings/java/native/digest.h
052a101b9d29efdd79fa0612486daa245db18289  bindings/java/native/Makefile
578cf878405ce06a0d995684dd0f66e4cba31808  bindings/java/native/bindings.h
92f2da049a6c6633fce6ba61b5d0786b94540cab  bindings/java/test/RHashTest.java
32f1f3b7406aba61d8bb6d6fa96a7333d3756bdc  bindings/java/src/org/sf/rhash/package-info.java
f1b2e974c87cf87683d9c332f90ec33dfcf936a5  bindings/java/src/org/sf/rhash/RHash.java
42a0a367c03f14ac0937b2e0984ed6060af5079e  bindings/java/src/org/sf/rhash/Digest.java
c12db54a64b6a8edefe828d6791f737693da5839  bindings/java/src/org/sf/rhash/HashType.java
bf2e6000adb247a055513858fa20e62ee4b3a95b  bindings/java/src/org/sf/rhash/Bindings.java
bce77483762fad39e09bc7ca14ab7e1b1026e66c  bindings/mono/Bindings.cs
0e7c0b0701b5c06a3b286cf621400776a0910c7f  bindings/mono/RHash.dll.config
a07c210e92da9dd5e40dce98a795f9d3802785a5  bindings/mono/.gitignore
e790e1daa39b6f540048107d5ae4b635e48b6d4c  bindings/mono/RHash.snk
e23dec91fff7dde7293a0f200dc112f40bcca24d  bindings/mono/AssemblyInfo.cs
70b58100d6ff2f21821eeaacb476e4556850f686  bindings/mono/Makefile
2e1be7b94944fa0669622d343e9040ba054512b7  bindings/mono/RHash.sln
e4faf5c0b415373d0ea04d6407983394d32fa005  bindings/mono/HashType.cs
0178871b60403cb53edb51870e0b992aa3d4385e  bindings/mono/RHash.csproj
94e87e52e8f3779aa89c47fc6580bb2f9832abf6  bindings/mono/Hasher.cs
9eed0483ffd417f175f84f686b20492b0c203864  bindings/mono/test/Makefile
908fbec68800d5436fd353d2481af41a4cad15f2  bindings/mono/test/Test.cs
2672275fe0c456fb671e4f417fb2f9892c7573ba  bindings/mono/test/12345.txt
bb64bd3eb9b45f18a4214f99404008fbd4255874  bindings/mono/doc/index.xml
f2410c914ef47d07dc2e50a2585eeba044e16747  bindings/mono/doc/ns-RHash.xml
9f589d5a71a2d501081d2e8d255217bbc2569a4d  bindings/mono/doc/RHash/HashType.xml
3d1f373212bf0311ddb49e3ecc0038ec1296b8ba  bindings/mono/doc/RHash/Hasher.xml

**Comment by rhash** [comment]
@rbiro thanks for reporting the bug.

It is fixed by 3af08c44eb106def9b4a43f594512bdd9f31f419.

**Comment by rhash** [comment]
Fix included in v1.3.9.
