### ISSUE TITLE
Windows VC 2010 - compile errors and EXE size

### ISSUE THREAD

**Issue by lab2k1** [rhash/RHash#91]
Getting the VC 2010 build to work requires a couple of source changes:

* an `#include <io.h> /* for isatty */` in `output.c`;

* an `#ifdef _MSC_VER #define inline __inline #endif` somewhere (see [here](https://stackoverflow.com/a/24736425) why).

With those changes, `rhash` builds, but the release x86 `rhash.exe` is 271 KB, while the pre-built one released with v1.3.8 comes at 2 MB. I guess this has something to do with the different build options, but it's not obvious to me which ones specifically.

Also, the official x86 `rhash.exe` grew in size from 368 KB in v1.3.3 to 2 MB in v1.3.8 and, on a cursory reading of the changelog, it's not obvious to me where the rather large increase came from.

Thank you for any insights.

**Comment by rhash** [comment]
@lab2k1, thanks for reporting this bug. Compilation is now fixed by commit fd34e76e982763681e834a820ca8668ea9b76f55.

The size of the binary has increased because of localization support - gettext library is statically linked into rhash.exe.

**Comment by rhash** [comment]
Fix included in v1.3.9.

**Comment by lab2k1** [comment]
Thank you, Aleksey!
