### ISSUE TITLE
Calculate hash in a temporal folder

### ISSUE THREAD

**Issue by khepper** [rhash/RHash#95]
I want to calculate some hash for a large number of files, (6-8tb) 
these information is in an external harddisk attached by usb. The access to this information is very slow and check crc32, md5, ed2k, sha1 is very very slow (and maybe damage the device)
But, if there is a way to copy the file to a local harddisk, calculate the hash and continue with the next, it will be faster and no dander for the device.
There is a way to do it? It can be a request?
Thanks in advantage

**Comment by rhash** [comment]
Copying a file to local harddisk will take the same time as calculating its hash directly from usb device. If you calculate the hash after copying, it'll take additional time, so the whole process will slower.

**Comment by khepper** [comment]
Hi rhash, thanks for your time

This is good for one hash, but in my case, I need to calculate more hashes, crc32, md5, sha1, ed2k and aich. In that case, the time is higher if the speed read is slow. Obviously, if the cache is an internal ssd hard disk, it will be faster

Thankls for all

**Comment by rhash** [comment]
You can see in the RHash [README](https://github.com/rhash/RHash/blob/master/README.md) and on its [web page](http://rhash.sf.net/) that RHash:
- Calculates several hash sums in one pass.

It means, RHash reads a file only once, calculating its hash sums simultaneously.

**Comment by khepper** [comment]
Great option, I'll check it
I'm newbie in rhash, I'm fighting with the command line yet
Thanks for your support
