### ISSUE TITLE
rhash ignoring quotation marks around filenames

### ISSUE THREAD

**Issue by henrypijames** [rhash/RHash#98]
rhash 1.3.8 on Windows 10 x64

I try to hash a file named `-123.txt` (notice the hyphen at the start):
```
rhash -123.txt
```

This is a syntax error, sure. But now I put the filename in quotation marks:
```
rhash "-123.txt"
```

This still doesn't work - rhash is not recognizing the quotation marks.

**Comment by rhash** [comment]
Use double dash: `rhash -- -123.txt`

From RHash [manual](http://rhash.sourceforge.net/manpage.php):
> -- (double dash)
> Mark the end of command line options. All parameters following the double dash are interpreted as files or directories. It is typically used to process **filenames starting with a dash ‘-’**. Alternatively you can specify ’./’ or full path before such files, so they will not look like options anymore.

**Comment by henrypijames** [comment]
I know that double dash. But is there any reason why quotation marks shouldn't also work?

**Comment by rhash** [comment]
Quotation is stripped by command shell. Filename is passed to the program without quotation, and the program can't detect that it has been present.
