### ISSUE TITLE
RFE: Quick way to confirm hash 

### ISSUE THREAD

**Issue by henrypijames** [rhash/RHash#99]
It would be nice to have a quick way to check a file against its supposed hash, without having to create a hash file first. Maybe something like:
```
rhash -f -M file1.txt::11111111 file2.txt::22222222
```
And the output would be:
```
file1.txt 11111111 confirmed
file2.txt 22222222 MISMATCH, actual hash: 22223333
````

**Comment by KevinBlue18** [comment]
You can make an output file `-o= _Filename_ `

**Comment by henrypijames** [comment]
@KevinBlue18 I don't understand what that command line of yours is supposed to do, but I'm pretty sure it's not doing what I want.

**Comment by rhash** [comment]
@henrypijames try: 
~~~sh
echo filepath hashsum | rhash -c -
~~~
E.g. `echo empty_file.txt 00000000 | rhash -c -`

**Comment by henrypijames** [comment]
Right, and if I want to check several files at once I'd need `sed` to chain the lines together? But I'm on Windows so piping capability is really limited.

**Comment by rhash** [comment]
You should use scripting languages for such tasks.

For example Windows batch script:
~~~cmd
@rem Usage: check-crc32.cmd [ FILEPATH::HASH ]...
@echo off

(
  @echo off
  for %%x in (%*) do (
    for /F "tokens=1,2 delims=::" %%a in ("%%~x") do (
      @echo %%a %%b
    )
  )
) | rhash.exe --crc32 -v -c -
~~~

Usage:
~~~cmd
D:\>check-crc32.cmd "file1.txt::11111111" file2.txt::00000000

--( Verifying (stdin) )---------------------------------------------------------
file1.txt                                           ERROR, CRC32 is 00000000 should be 11111111
file2.txt                                           OK
--------------------------------------------------------------------------------
Errors Occurred: Errors:1   Miss:0   Success:1   Total:2
~~~
